### PR TITLE
new pretty JSON format + severity level filter

### PR DESCRIPTION
**Pull request by AlGreed**
#385
- added a structured JSON format (use --json-pretty or --jsonfile-pretty <file>)

```
./testssl.sh --json-pretty url:port
```
- added severity level filter (use --severity)

```
./testssl.sh --json-pretty --severity "CRITICAL" url:port
```

Quality:
- manual testing
- clean up code with shellcheck
- perl test /t/01_badssl.com.t

P.S. it seems Intellij removed some empty spaces and empty code lines.

### CODE REVIEW

**Comment by drwetter** [comment]
Thanks a lot @AlGreed, Cool! Integration is very smooth and even the flat output from @seccubus can deal now with severities.. Tip off the hat

One request though: Could you please update your PR to the recent 2.9dev? It's pretty behind.

**Comment by AlGreed** [comment]
> One request though: Could you please update your PR to the recent 2.9dev? It's pretty behind.
Done.

**Comment by drwetter** [comment]
Thanks for your contribution! (what's tour twitter handle?)

**Comment by AlGreed** [comment]
Gerne :)

@a1gr33d,  @whatevermobile

**Pull request merged**
