### PR TITLE
Fixing issue #988

### PR DESCRIPTION
**Pull request by danielchodusov**
This will fix empty trailing comma in JSON output #988

### CODE REVIEW

**Comment by drwetter** [comment]
Hi Daniel,

thx for the PR but that should be fixed, see commit in the referenced, closed issue.

Or do still see this? If so please provide details.

Thx, Dirk
-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by danielchodusov** [comment]
Hello Dirk,

yes it's not fixed yet - still problem with ALPN. Try this website:

testssl.sh --fast --parallel --sneaky --quiet --ip=one -o out.json hrad.cz and see line 62 by - 63 the line is ending with comma.

This fix will insert "(empty)" value as @seccubus suggested in his fix.
screen shot 2018-03-13 at 11 39 11

**Comment by drwetter** [comment]
My improvement in #988 wasn't complete, i.e. when HTTP/2 is the only protocol you ran into the same problem. Like you did.

But as said in seccubus' PR: The fix should be better at the root cause, rater than patching an output function if a string is empty. So, thanks for the PR, Daniel. My fix follows

**Comment by drwetter** [comment]
PS: ``-parallel`` currently only makes sense if you test more than 1 host.

**Pull request closed without merging**
