### PR TITLE
A ClientHello length intolerance bug

### PR DESCRIPTION
**Pull request by dcooper16**
Just as some servers will fail if the length of the ClientHello is between 256 and 511 bytes (see RFC 7685), it seems that some servers (or a middlebox sitting in front of the servers) will fail if the length of the ClientHello is 522, 778, 1034, ... bytes (i.e., if length **mod** 256 = 10). I have also encountered one server that will also fail if the length of the ClientHello is 526, 782, 1038, ... bytes (i.e., if length **mod** 256 = 14).

In the case of that one server, the first ClientHello sent by run_pfs() was exactly 1038 bytes, and so run_pfs() was reporting that the server didn't support any PFS ciphers even though it did.

This PR addresses the problem in two ways. First, it modifies socksend_tls_clienthello() so that if the length of the ClientHello would be more than 511 bytes and length **mod** 256 would be 10 or 14, it adds a 5-byte padding extension in order to ensure that the final length of the ClientHello will not be a length that could trigger the bug.

Second, this PR adds a test to run_grease() to send ClientHello messages of the exact lengths that do trigger the bug so that users can be made aware that their servers have the problem.

### CODE REVIEW

**Comment by drwetter** [comment]
Has anybody else seen such an intolerance

@PeterMosmans @jurajsomorovsky?

**Comment by jurajsomorovsky** [comment]
@ic0ns recently spotted something similar in the wild. Is it true?

**Comment by ic0ns** [comment]
Not directly like this, but some server only allow a certain number of ciphersuites. Eg. if you propose more than 256 (512 Byte) ciphersuites the server won't answer you.

**Comment by dcooper16** [comment]
> Not directly like this, but some server only allow a certain number of ciphersuites. Eg. if you propose more than 256 (512 Byte) ciphersuites the server won't answer you.

Yes, that's a different issue that we already knew about. testssl.sh already checks for that and generally sends 128 or fewer cipher suites in each ClientHello message.

**Comment by dcooper16** [comment]
I just submitted a few updates to this PR:

* I removed the changes to socksend_tls_clienthello() - these will be submitted as a separate PR.

* I added a test for a ClientHello message length of 266 bytes, but only if the server can generally handle messages with lengths between 256 and 511 bytes.

* I corrected the calculation of the length of the padding extension in cases in which a TLS 1 or TLS 1.1 ClientHello is being sent.

**Comment by drwetter** [comment]
Thanks!

**Comment by drwetter** [comment]
@tomato42 : does this incompatibility (ClientHello  522, 778, 1034 / 526, 782, 1038 -- see above) ring a bell?

**Comment by tomato42** [comment]
@drwetter it does, but very mildly - it might have been some kind of Cisco gear but I'm really not sure about it (one that would reject CH above 512B long)

but in general it looks like there are different implementations with bugs like this, see the `size c#/` (count of ciphers in CH) and `size c/` (size of the CH in bytes) lines in the last scan I did [January 2017](https://securitypitfalls.wordpress.com/2017/04/17/january-2017-scan-results/)

if you have a machine like this on hand, what does the [`tls_prober`](https://github.com/WestpointLtd/tls_prober) say about it?

**Comment by drwetter** [comment]
@tomato42 : you mean Cisco ACE? yeah, that was the one with 512B restriction IIRC.

There are couple of servers @dcooper16 mentioned. Most often was 11.4 or 11.5 from F5's BigIP. 
If that's true seems a different problem they have.

Shouldn't that cause hiccups elsewhere?

**Comment by tomato42** [comment]
no, the rejection of 256-511 byte CH was the BigIP, rejection of the 512B CH was something typically not used for serving web, not the ACE

> Shouldn't that cause hiccups elsewhere?

it could, but browsers are usually really careful with changes to their CH and running multiple tests before actually deploying them (even to alpha channels)

> `size c# | size c/ ` match: doesn't look like it but thanks

hmm, could be because those values were arrived at with binary search so something regular would require one of the probes hitting it exactly, also IIRC, those probes were run only if the server was intolerant to very big CH (like 130kB big), so if they handled that well, it wouldn't be detected

**Comment by PeterMosmans** [comment]
@drwetter I only know of the Cisco ACE issues with large Client Hellos..

**Comment by drwetter** [comment]
@tomato42 Yes, I remember very good the old problem. What I meant that it seems that maybe F5 has another padding problem

**Comment by drwetter** [comment]
FYI: It's in fact F5 BigIP. Kudos for @dcooper16 detecting this.

**Comment by saravananmk** [comment]
> FYI: It's in fact F5 BigIP. 

@drwetter  @dcooper16  The ClientHello length intolerance on F5 BIGIP is due to https://support.f5.com/csp/article/K53322151

**Comment by tomato42** [comment]
@saravananmk you mean the F5 KB is incomplete? because I don't think the 522B Client Hello would be fragmented...

**Comment by drwetter** [comment]
I read that different, too

**Comment by saravananmk** [comment]
> @saravananmk because I don't think the 522B Client Hello would be fragmented...

I observed the following (testssl.sh 3.0rc1) 

ClientHello length is 266 bytes: TCP seg#1: 5 bytes, seg#2: 266 bytes.
ClientHello length is 522 bytes: TCP seg#1: 5 bytes, seg#2: 522 bytes.
ClientHello length is 778 bytes: TCP seg#1: 5 bytes, seg#2: 778 bytes.
ClientHello length is 1034 bytes: TCP seg#1: 5 bytes, seg#2: 1034 bytes.
ClientHello length is 1290 bytes: TCP seg#1: 5 bytes, seg#2: 1290 bytes.
ClientHello length is 1546 bytes: TCP seg#1: 5 bytes, seg#2: 1448 bytes, seg#3: 98 bytes.
ClientHello length is 1802 bytes: TCP seg#1: 5 bytes, seg#2: 1448 bytes, seg#3: 354 bytes.
ClientHello length is 2058 bytes: TCP seg#1: 5 bytes, seg#2: 1448 bytes, seg#3: 610 bytes.

So I still believe it is that F5 KB (K53322151).

**Comment by tomato42** [comment]
so the record layer header is sent in a separate TCP segment? that would seem like a bug in testssl.sh... But then if that split is constant it would make testssl.sh unable to scan any F5 hosts suffering from K53322151

**Comment by drwetter** [comment]
Isn't the TCP fragment size negotiated on a different (not TLS/SSL) layer?

**Comment by saravananmk** [comment]
> But then if that split is constant it would make testssl.sh unable to scan any F5 hosts suffering from K53322151

Another observation: (testssl.sh 3.0rc1)

The following does not hit the K53322151 because as per the F5 KI, to hit it
"The length of the first fragment is less than 8 bytes."

ClientHello length is 526 bytes: TCP seg#1: 9 bytes, seg#2: 522 bytes.
ClientHello length is 782 bytes: TCP seg#1: 9 bytes, seg#2: 778 bytes.

**Comment by tomato42** [comment]
> Isn't the TCP fragment size negotiated on a different (not TLS/SSL) layer?

if the testssl.sh doesn't send the data in a single syscall, then coalescing of writes may not always happen (because of Nagle)

**Comment by drwetter** [comment]
> if the testssl.sh doesn't send the data in a single syscall, then coalescing of writes may not always happen (because of Nagle)

We're opening a bash socket, that's it. Syscalls are transparent to us and there's no direct way of telling when packets split. Also at least the extreme split into a tiny segment and then a chunk seems to be F5 related.

@saravananmk : In https://github.com/drwetter/testssl.sh/pull/1113#issuecomment-423456972: what check were you running?

**Comment by dcooper16** [comment]
I also now believe this bug is most likely really https://support.f5.com/csp/article/K53322151. After this PR was merged, some independent testing determined that versions 12.1.3.2 and later and 13.1.0 and later did not fail these tests. From that I found K53322151 and did some further testing, using Wireshark to observe how messages were being fragmented.

I already knew that when sending the ClientHello using Bash sockets the message tended to get broken into a number of small fragments. To my extreme surprise I discovered that while in most cases the first fragment was 34 bytes, the first fragment was only 5 bytes whenever length **mod** 256 = 10 and it was 9 bytes whenever length **mod** 256 = 14.

As @drwetter noted, the fragmentation is transparent to us, as it is happening at a lower layer, so I was only aware of the length of the ClientHello, not how it was being fragmented. I never would have guessed that the length of the first fragment would be shorter if and only if the overall length of the message was such that TLSCiphertext.length **mod** 256 is 10 or 14.

But, it does seem that the reason that the connection failed only when TLSCiphertext.length **mod** 256 was 10 was not because of the length of the message, but because of the different way in which the underlying transport layer was fragmenting messages of these lengths.

**Comment by tomato42** [comment]
> We're opening a bash socket, that's it.

yes, but do you write to it using a single `echo` or multiple calls? If there are multiple calls, then that may leak to TCP level and it's what we see here

**Comment by dcooper16** [comment]
> > We're opening a bash socket, that's it.
> 
> yes, but do you write to it using a single echo or multiple echo calls? If there are multiple echo calls, then that may leak to TCP level and it's what we see here

The entire ClientHello is being sent with a single call:
```
     printf -- "$data" >&5 2>/dev/null &
```
where `$data` contains the entire ClientHello message and `5` is the socket to which the data is being written.

I've tried searching for information on why the messages are being fragmented when they could be sent in a single packet, but I haven't been able to find anything. In most cases the fragmenting hasn't affected the results of the testing, but it must hurt performance.

**Comment by saravananmk** [comment]
> Also at least the extreme split into a tiny segment and then a chunk seems to be F5 related.

The outgoing packets of the ClientHello were generated by Linux client machine (Ubuntu) and hence nothing to do with F5.

For e.g. I did another test running testssl.sh on Kali linux and running openssl s_server on Ubuntu.  No F5 involved.  And I can clearly see the TCP getting fragmented.  In this test:

ClientHello length is 522 bytes: TCP seg#1: 9 bytes, seg#2:  522 bytes.

**Comment by tomato42** [comment]
> > > We're opening a bash socket, that's it.
> > 
> > 
> > yes, but do you write to it using a single echo or multiple echo calls? If there are multiple echo calls, then that may leak to TCP level and it's what we see here
> 
> The entire ClientHello is being sent with a single call:
> 
> ```
>      printf -- "$data" >&5 2>/dev/null &
> ```
> 
> where `$data` contains the entire ClientHello message and `5` is the socket to which the data is being written.

yes, but does that ClientHello message written include Handshake protocol header and Record Layer header? Can you provide an example of that `$data`? first 16 bytes or so would be enough

**Comment by dcooper16** [comment]
> yes, but does that ClientHello message written include Handshake protocol header and Record Layer header? Can you provide an example of that $data? first 16 bytes or so would be enough

Yes, it includes everything. Here is an example:
```
printf -- '\x16\x03\x01\x2\x00\x01\x00\x1\xfc\x03\x03\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x20\x44\xb8\x92\x56\xaf\x74\x52\x9e\xd8\xcf\x52\x14\xc8\xaf\xd8\x34\x0a\xe7\x7f\xeb\x86\x01\x84\x50\x5d\xe4\xa1\x6a\x09\x3b\xbf\x6e\x00\x0a\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05\x01\x00\x1\xa9\x00\x23\x00\x00\x33\x74\x00\x00\x00\x0d\x00\x22\x00\x20\x04\x03\x05\x03\x06\x03\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x08\x09\x08\x0a\x08\x0b\x08\x07\x08\x08\x02\x01\x02\x03\x00\x0a\x00\x10\x00\x0e\x00\x1d\x00\x17\x00\x1e\x00\x18\x00\x19\x01\x00\x01\x01\x00\x33\x00\x6b\x00\x69\x00\x1d\x00\x20\xad\xda\x32\xb8\xc8\x41\xc6\x0a\xa3\xcd\x37\x92\xf3\x4f\xa2\x4a\x97\x84\xb4\xc9\x2c\x54\xc5\x70\xab\xd1\x10\xea\xcd\x7b\x6b\x42\x00\x17\x00\x41\x04\x24\xfd\xc6\xa1\x9c\x95\x62\xb6\x9b\x39\xab\x89\x31\x65\x19\x27\x13\x34\x3c\x46\xed\x8d\x3c\x56\xec\xaf\x15\xf8\x93\x03\x84\x96\xbe\x53\x24\x50\x9b\xc4\xdf\xd8\xb0\xe7\xcc\x20\x22\xbb\x0c\xc5\xf2\x6d\x0a\x85\xc9\x68\x1c\x4a\x29\xb4\x3d\x96\x05\x49\x89\x95\x00\x0b\x00\x02\x01\x00\x00\x2b\x00\x0f\x0e\x03\x04\x7f\x1c\x7f\x1b\x7f\x1a\x7f\x19\x7f\x18\x7f\x17\x00\x0f\x00\x01\x01\x00\x15\x00\xd6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```
According to Wireshark, this message is being broken into 8 TCP segments:
```
[8 Reassembled TCP Segments (517 bytes): #29(34), #31(27), #33(17), #35(50), #37(12), #39(36), #41(80), #43(261)]
  [Frame: 29, payload: 0-33 (34 bytes)]
  [Frame: 31, payload: 34-60 (27 bytes)]
  [Frame: 33, payload: 61-77 (17 bytes)]
  [Frame: 35, payload: 78-127 (50 bytes)]
  [Frame: 37, payload: 128-139 (12 bytes)]
  [Frame: 39, payload: 140-175 (36 bytes)]
  [Frame: 41, payload: 176-255 (80 bytes)]
  [Frame: 43, payload: 256-516 (261 bytes)]
[Segment count: 8]
[Reassembled TCP length: 517]
```

**Comment by tomato42** [comment]
Looks like line buffering interfering:

```python
>>> a = '\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x20\x44\xb8\x92\x56\xaf\x74\x52\x9e\xd8\xcf\x52\x14\xc8\xaf\xd8\x34\x0a\xe7\x7f\xeb\x86\x01\x84\x50\x5d\xe4\xa1\x6a\x09\x3b\xbf\x6e\x00\x0a\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05\x01\x00\x01\xa9\x00\x23\x00\x00\x33\x74\x00\x00\x00\x0d\x00\x22\x00\x20\x04\x03\x05\x03\x06\x03\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x08\x09\x08\x0a\x08\x0b\x08\x07\x08\x08\x02\x01\x02\x03\x00\x0a\x00\x10\x00\x0e\x00\x1d\x00\x17\x00\x1e\x00\x18\x00\x19\x01\x00\x01\x01\x00\x33\x00\x6b\x00\x69\x00\x1d\x00\x20\xad\xda\x32\xb8\xc8\x41\xc6\x0a\xa3\xcd\x37\x92\xf3\x4f\xa2\x4a\x97\x84\xb4\xc9\x2c\x54\xc5\x70\xab\xd1\x10\xea\xcd\x7b\x6b\x42\x00\x17\x00\x41\x04\x24\xfd\xc6\xa1\x9c\x95\x62\xb6\x9b\x39\xab\x89\x31\x65\x19\x27\x13\x34\x3c\x46\xed\x8d\x3c\x56\xec\xaf\x15\xf8\x93\x03\x84\x96\xbe\x53\x24\x50\x9b\xc4\xdf\xd8\xb0\xe7\xcc\x20\x22\xbb\x0c\xc5\xf2\x6d\x0a\x85\xc9\x68\x1c\x4a\x29\xb4\x3d\x96\x05\x49\x89\x95\x00\x0b\x00\x02\x01\x00\x00\x2b\x00\x0f\x0e\x03\x04\x7f\x1c\x7f\x1b\x7f\x1a\x7f\x19\x7f\x18\x7f\x17\x00\x0f\x00\x01\x01\x00\x15\x00\xd6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
>>> a[33]
'\n'
>>> a[60]
'\n'
>>> a[77]
'\n'
>>> a[127]
'\n'
>>> a[139]
'\n'
>>> a[175]
'\n'
>>> a[255]
'\n'
```

**Comment by drwetter** [comment]
> For e.g. I did another test running testssl.sh on Kali linux and running openssl s_server on Ubuntu. No F5 involved. And I can clearly see the TCP getting fragmented. In this test:
> 
> ClientHello length is 522 bytes: TCP seg#1: 9 bytes, seg#2: 522 bytes.

That's not when I see when I run e.g. ``testssl.sh --assume-http -g testssl.sh``. Every ClientHello (except the first where I think OpenSSL is being used) is split in two fragments, #\1 being 34 bytes net (on the wire: 100 bytes), \#2 the rest

**Comment by drwetter** [comment]
@tomato42 you seem to have a point here.

**Comment by dcooper16** [comment]
> @tomato42 you seem to have a point here.

This does seem to explain what is happening. Is there anything that can be done about it?

**Comment by drwetter** [comment]
escaping the lf or looking for the right printf format specifier (``%b`` doesn't work)

**Comment by drwetter** [comment]
``/usr/bin/printf`` does no flush of all data if a LF is encountered

**Comment by drwetter** [comment]
522, 778, 1034, .. all contained an '\x0a' in the record layer.  That's likely the hiccup in F5 where we sent a new fragment after '\x0a'. The handshake message data length is typically four bytes later, this explains why some with a ClientHello of 526, 782, 1038 .. byes failed

**Comment by saravananmk** [comment]
@dcooper16  @tomato42 

> Yes, it includes everything. Here is an example:
> 
> ```
> printf -- '\x16\x03\x01\x2\x00\x01\x00\x1\xfc\x03\x03\x54\x51\x1e\x7a\xde\xad\xbe\xef\x31\x33\x07\x00\x00\x00\x00\x00\xcf\xbd\x39\x04\xcc\x16\x0a\x85\x03\x90\x9f\x77\x04\x33\xd4\xde\x20\x44\xb8\x92\x56\xaf\x74\x52\x9e\xd8\xcf\x52\x14\xc8\xaf\xd8\x34\x0a\xe7\x7f\xeb\x86\x01\x84\x50\x5d\xe4\xa1\x6a\x09\x3b\xbf\x6e\x00\x0a\x13\x01\x13\x02\x13\x03\x13\x04\x13\x05\x01\x00\x1\xa9\x00\x23\x00\x00\x33\x74\x00\x00\x00\x0d\x00\x22\x00\x20\x04\x03\x05\x03\x06\x03\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x08\x09\x08\x0a\x08\x0b\x08\x07\x08\x08\x02\x01\x02\x03\x00\x0a\x00\x10\x00\x0e\x00\x1d\x00\x17\x00\x1e\x00\x18\x00\x19\x01\x00\x01\x01\x00\x33\x00\x6b\x00\x69\x00\x1d\x00\x20\xad\xda\x32\xb8\xc8\x41\xc6\x0a\xa3\xcd\x37\x92\xf3\x4f\xa2\x4a\x97\x84\xb4\xc9\x2c\x54\xc5\x70\xab\xd1\x10\xea\xcd\x7b\x6b\x42\x00\x17\x00\x41\x04\x24\xfd\xc6\xa1\x9c\x95\x62\xb6\x9b\x39\xab\x89\x31\x65\x19\x27\x13\x34\x3c\x46\xed\x8d\x3c\x56\xec\xaf\x15\xf8\x93\x03\x84\x96\xbe\x53\x24\x50\x9b\xc4\xdf\xd8\xb0\xe7\xcc\x20\x22\xbb\x0c\xc5\xf2\x6d\x0a\x85\xc9\x68\x1c\x4a\x29\xb4\x3d\x96\x05\x49\x89\x95\x00\x0b\x00\x02\x01\x00\x00\x2b\x00\x0f\x0e\x03\x04\x7f\x1c\x7f\x1b\x7f\x1a\x7f\x19\x7f\x18\x7f\x17\x00\x0f\x00\x01\x01\x00\x15\x00\xd6\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
> ```
> According to Wireshark, this message is being broken into 8 TCP segments:

I tried the same bytes.  In my testing on Ubuntu linux, it got fragmented into only 2 TCP segments:

0-33 in first segment (34 bytes)
34-516 in second segment (483 bytes)

Reassembled TCP length: 517.  

So looks like it is not fragmenting every single time it encounters 0x0a.  I have more samples like this in case if you want.

**Comment by drwetter** [comment]
which git revision? With the recent updates that should be off the table, under Linux at least, see logs above.

**Comment by saravananmk** [comment]
> which git revision? With the recent updates that should be off the table, under Linux at least, see logs above.

Sorry if my previous comment confused you.  I am referring to bash printf fragmentation behaviour in general.  My comment was not meant for the fixed version of testssl.  For the above fragmentation test (https://github.com/drwetter/testssl.sh/pull/1113#issuecomment-426576678) , I used a simple bash script with inbuilt printf command to send the TCP content to the socket.

**Comment by drwetter** [comment]
No prob. 

I also see two fragments only but 7x LF in the example. The answer will be probably interesting -- but for the project I think it matters not much. Any fragmentation is not what we want. So whether it is 2 or 8: we don't care. Generally we will move to dd sometime.

The bash maintainers said that the internal printf is line buffered per design. Why for you and me the other LFs don't cause additional fragmentations -- that has to be answered by the bash maintainers. :-)

**Comment by drwetter** [comment]
Big thanks to @tomato42 btw!

**Pull request merged**
