### PR TITLE
Use sockets for client simulations

### PR DESCRIPTION
**Pull request by dcooper16**
Modify run_client_simulation() to send the ClientHello from https://api.dev.ssllabs.com/api/v3/getClients (modified to use the correct value in the server name extension) if $EXPERIMENTAL is true, $STARTTLS is empty, and $SSL_NATIVE is false.

### CODE REVIEW

**Comment by drwetter** [comment]
That's absolutely awesome, @dcooper16 !

It would not hurt atm to merge this. Except the TLS1.0 vs. TLS1 thing, there seem to be some differences though:

```
- Start 2016-06-24 18:19:51    -->> 81.169.199.25:443 (dev.testssl.sh) <<--
+ Start 2016-06-24 18:08:59    -->> 81.169.199.25:443 (dev.testssl.sh) <<--
 
  further IP addresses:   2a01:238:4279:1200:1000:1:e571:51
  rDNS (81.169.199.25):   testssl.sh.
@@ -14,8 +14,8 @@
  Android 4.0.4                 TLSv1 ECDHE-RSA-DES-CBC3-SHA
  Android 4.1.1                 TLSv1 ECDHE-RSA-DES-CBC3-SHA
  Android 4.2.2                 TLSv1 ECDHE-RSA-DES-CBC3-SHA
- Android 4.3                   TLSv1 ECDHE-RSA-DES-CBC3-SHA
- Android 4.4.2                 TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
+ Android 4.3                   TLSv1.0 ECDHE-RSA-DES-CBC3-SHA
+ Android 4.4.2                 TLSv1.1 ECDHE-RSA-DES-CBC3-SHA
  Android 5.0.0                 TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
  Baidu Jan 2015                TLSv1 ECDHE-RSA-RC4-SHA
  BingPreview Jan 2015          TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
@@ -24,17 +24,17 @@
  Firefox 42 / OSX              TLSv1.2 DES-CBC3-SHA
  GoogleBot Feb 2015            TLSv1.2 ECDHE-RSA-RC4-SHA
  IE6 / XP                      No connection
- IE7 / Vista                   TLSv1 RC4-SHA
+ IE7 / Vista                   TLSv1.0 RC4-SHA
  IE8 / XP                      No connection
- IE8-10 / Win7                 TLSv1 RC4-SHA
- IE11 / Win7                   TLSv1.2 RC4-SHA
+ IE8-10 / Win7                 TLSv1.0 DES-CBC3-SHA
+ IE11 / Win7                   TLSv1.2 DES-CBC3-SHA
  IE11 / Win8.1                 TLSv1.2 DES-CBC3-SHA
- IE10 / Win Phone 8.0          TLSv1 RC4-SHA
+ IE10 / Win Phone 8.0          TLSv1.0 RC4-SHA
  IE11 / Win Phone 8.1          TLSv1.2 DES-CBC3-SHA
  IE11 / Win Phone 8.1 Update   TLSv1.2 DES-CBC3-SHA
  IE11 / Win10                  TLSv1.2 DES-CBC3-SHA
  Edge 13 / Win10               TLSv1.2 DES-CBC3-SHA
- Edge 13 / Win Phone 10        TLSv1.2 DES-CBC3-SHA
+ Edge 12 / Win Phone 10        TLSv1.2 DES-CBC3-SHA
  Java 6u45                     No connection
  Java 7u25                     TLSv1 ECDHE-RSA-RC4-SHA
  Java 8u31                     TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
@@ -51,6 +51,6 @@
  Safari 9 / iOS 9              TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
  Safari 9 / OS X 10.11         TLSv1.2 ECDHE-RSA-DES-CBC3-SHA
 
- Done 2016-06-24 18:20:03    -->> 81.169.199.25:443 (dev.testssl.sh) <<--
+ Done 2016-06-24 18:09:13    -->> 81.169.199.25:443 (dev.testssl.sh) <<--
```

(correlates with your patch somewhat). How come ? Is the data @seccubus used a while back out dated? If so it should be merged rather sooner then later.

Cheers, Dirk

**Comment by drwetter** [comment]
Setting ``EXPERIMENTAL=true`` I am only able to see the protocol, no cipher -- if the mapping file cannot be found. No showstopper but maybe  at least it should bail out until we have the thing with the table.

 Doing a socket / non-socket diff it seems to match -- which is great. A bit hard to read though as for the non-socket version the output is ``TLSv1`` and not ``TLSv1.0``

**Comment by drwetter** [comment]
``TLSv1`` issue has been addressed, see 5cb4b72

**Comment by dcooper16** [comment]
I made a small change to the code so that the cipher will be printed even if the mapping file cannot be found. If `$MAPPING_FILE_RFC` is empty, then `parse_tls_serverhello()` looks for the cipher's hexcode in `$OPENSSL ciphers -V ALL:COMPLEMENTOFALL` and uses that, and then `run_client_simulation()` just uses the value from `$TMPFILE` rather than calling rfc2openssl().

In the long run, I would like to get rid of the call to `rfc2openssl()` and just display the RFC name when sockets are used, but that would make it difficult to compare the OpenSSL and sockets outputs.

@seccubus submitted a PR against my code (see https://github.com/seccubus/testssl.sh/tree/client_sim_sockets) where he regenerated the client data and moved it to a separate file. I copied the new client data into my version and there are only a few changes.

Hopefully any issues with the data not matching are addressed (except in cases where the OpenSSL version chooses the wrong cipher as a result of not taking supported curves into account). If not, we can use the results from https://www.ssllabs.com/sslest to try to determine which version is giving the incorrect results.

It's up to you whether you want to merge this PR now (and then merge in the improvements from @seccubus later) or wait until I've merged the improvement from @seccubus into my PR.

**Comment by drwetter** [comment]
Thx, David! 

@seccubus : I would rather wait to extend that _now_.  First step then would be anyway to list clients with a fixed set of ciphers, anything else would not make much sense to me. 

You know TLS fingerprinting project from @LeeBrotherston ? We would need to ask him though first...

Cheers, Dirk

**Comment by LeeBrotherston** [comment]
Hey there.  You're after lists of clients with fixed ciphersuite lists in their ClientHello packets?

**Comment by drwetter** [comment]
Hiho! Yup.

**Comment by seccubus** [comment]
For socket simulations we also need the raw client-hello messages. So far, this doesn't seem to be in @LeeBrotherston 's list. I see this list actually has signatures that SSL Labs doesn't have (stuff like mail clients and certain iOS apps) If we can augment the data and/and make testssl.sh handle missing data better that would be great.

Right now I defaulted back to parsing the ssllabs list.

**Comment by drwetter** [comment]
Am 29. Juni 2016 08:28:22 MESZ, schrieb Frank Breedijk <notifications@github.com>:
>For socket simulations we also need the raw client-hello messages. So
>far, this doesn't seem to be in @LeeBrotherston 's list. I see this
>list actually has signatures that SSL Labs doesn't have (stuff like
>mail clients and certain iOS apps) If we can augment the data and/and
>make testssl.sh handle missing data better that would be great.

I thought more of an additional source, not as a replacement. 


Cheers, Dirk


-- 
Set from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
Awesome what little beauties ;-) you have in there, @LeeBrotherston!

But see @seccubus answer ("For socket simulations we also need the raw client-hello messages"), see https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L1995-2747.

We started with checking this via sockets as otherwise we got false information in the client handshake, see https://github.com/drwetter/testssl.sh/issues/375#issuecomment-229282470

In the code I see you basically parse everything (what atm testssl.sh needs

**Comment by LeeBrotherston** [comment]
Ah yes I do, apologies I thought that you only wanted the ciphersuites.

If you would like the full packet info, I have a json file which has a lot more information:

https://github.com/LeeBrotherston/tls-fingerprinting/blob/master/fingerprints/fingerprints.json

They're not quite raw as they do not include things like sessionId or random number, but it does contain everything that remains static (I think)

**Pull request merged**
