### PR TITLE
Update testssl.sh

### PR DESCRIPTION
**Pull request by Blyzz616**
added new line character on line 17366

## Describe your changes

Please refer to an issue here or describe the change thouroughly in your PR.

What is your chnage about?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Typo fix
- [ ] Documentation update
- [ ] Update of other files

## If it's a code change please check the boxes which are applicable: 
- [x] For the main program: My edits contain no tabs and the indentation is five spaces
- [x] I've read CONTRIBUTING.md and Coding_Convention.md 
- [x] I have tested this __fix__ against >=2 hosts and I couldn't spot a problem
- [x] For the __new feature__ I have made corresponding changes to the documentation and / or to ``help()``
- [x] I have tested this __new feature__ against >=2 hosts which show this feature and >=2 host which does not (in order to avoid side effects) . I couldn't spot a problem
- [x] If it's a bigger change: I added myself to CREDITS.md (alphabetical order) and the change to CHANGELOG.md

### CODE REVIEW

**Comment by Blyzz616** [comment]
before change:

image


After change:
image

**Comment by drwetter** [comment]
Thanks a lot!

**Comment by Blyzz616** [comment]
I didn't test this - but you _might_ want to add another one on line 17371.

image


Also LOVE your script buddy. This is seriously awesome!

**Comment by drwetter** [comment]
@Blyzz616:  👍

**Pull request merged**
