### PR TITLE
Add Darwin x86 build

### PR DESCRIPTION
**Pull request by tunetheweb**
Think I did this right.

Followed instructions here: https://twitter.com/drwetter/status/1566044103741161477

And copied `openssl.Darwin.x86_64.dynamic` binary into bin dir and dropped the `.dynamic` extension.

### CODE REVIEW

**Comment by drwetter** [comment]
Cool, thank you!

Can you just do a single commit? If possible against the branch new_binaries, so that it shows up in PR #2223 ?

**Comment by tunetheweb** [comment]
I presumed I wouldn’t have direct access to branches in this repo?

Feel free to download this binary and commit yourself if that’s the case. Think of it as a thank you for making this great tool available!

**Comment by drwetter** [comment]
Hi @tunetheweb ,

thanks!

You issued a PT against 3.1dev. AFAIU new_binaries is just another branch here which will be merged into 3.1dev.

It's okay if I can just grab the binary (will do that tomorrow). You don't show up not in the git log then .

Cheers, Dirk

**Comment by tunetheweb** [comment]
Yup that’s cool. So close this PR after you do that.

**Comment by drwetter** [comment]
Thanks, @tunetheweb !

**Pull request closed without merging**
