### PR TITLE
Add Dependenbot checking for GitHub Actions

### PR DESCRIPTION
**Pull request by jauderho**

### CODE REVIEW

**Comment by drwetter** [comment]
Is this related to #1939 ? You lost me

**Comment by jauderho** [comment]
Not directly. It looks like you already have a GitHub Action in use so enabling Dependabot should help keep Action versions up to date.

**Comment by drwetter** [comment]
Thanks, @jauderho . You got to start picking me up where I am. :-) The only knowledge I have about dependabot is for other projects to warn about outdated binaries/libraries . 

The action version: isn't that maintained by GH ?

**Comment by jauderho** [comment]
@drwetter 

Each GH action is typically bound to a version for each action. See for example https://github.com/jauderho/dockerfiles/blob/a5f08c8e09241d8082f05fb77591af730f0d4536/.github/workflows/ansible.yml#L30

What dependabot can do is monitor the action for an updated version of the action and then submit a pull request for you to modify your "workflow.yml" to reflect the latest version. 

Here's an example of such a pull request

https://github.com/jauderho/dockerfiles/pull/28

Anyways, it's not a must-have but certainly a useful feature IMO

**Comment by drwetter** [comment]
Ok, thanks (merged).

**Pull request merged**
