### PR TITLE
Show server supported signature algorithms

### LINKED ISSUE #1519: Show peer signing digest / signed_params hash function
OS: `Ubuntu 19.10`

testssl.sh version:
```
testssl.sh       3.0 from https://testssl.sh/
(4dbd9a9 2020-02-15 15:23:07 -- )
commit 4dbd9a98ba503f624b24d00629da0e98d655021c
```
OpenSSL used:
```
./bin/openssl.Linux.x86_64
```
Chrome is looking to deprecate the RSA SHA-1 signing digest: https://bugs.chromium.org/p/chromium/issues/detail?id=658905

This is not the signature algorithm of the certificate, nor the HMAC of the cipher suite, but (I think) the algorithm used to sign the server parameters during the handshake.

An example site (taken from this Mozilla ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1600449) is https://www.daserste.de/.

In the Firefox developer tools, you can see in the "Network" tab of a request, and then in the "Security" sub-tab, it says: "Signature Scheme": `RSA-PKCS1-SHA1`.

This can also be seen in the OpenSSL output:
```
openssl s_client -connect www.daserste.de:443 -servername www.daserste.de
```
```
Peer signing digest: SHA1
Peer signature type: RSA
```
There is a ticket for adding this to SSL Labs here: https://github.com/ssllabs/ssllabs-scan/issues/465

It would be really useful to add to testssl.sh. Thank you.

### PR DESCRIPTION
**Pull request by dcooper16**
This PR fixes #1519 by modifying `run_fs()` to show the signature algorithms the server supports in the ServerKeyExchange message for TLS 1.2 and in the CertificateVerify message for TLS 1.3.

Signature algorithms are not shown for TLS 1.1 and earlier, since for those protocol versions the signature algorithm to use is specified by the protocol. While the signature algorithm used in TLS 1.1 and earlier is weak, testssl.sh already warns if these protocol versions are supported.

The code in this PR includes an initial proposal for the rating the set of supported signature algorithms, but it likely needs some changes. It assigns a rating of CRITICAL if the server only supports signature algorithms that use MD5 or SHA1. I assigned the worst rating to this case, since it was my understanding that this could lead to interoperability problems. If the server supports stronger algorithms, but also supports MD5, that is rated HIGH. Support for SHA1 is rated LOW.

Given that TLS 1.1 and earlier use SHA1 or SHA1+MD5 as the hash, it seems that using SHA1 with TLS 1.2 is no worse than using TLS 1.1 or earlier. So, the rating for supporting SHA1 should be no worse than the rating for supporting TLS 1.1 (see #1251).

### CODE REVIEW

**Comment by drwetter** [comment]
Hi David,

thanks for your work.

For a reasonable up-to-date web server (testssl.sh) the patch costs at least 5 seconds, in a worse case 10 seconds. Not sure why at the moment. But if you have an idea why, it would be great to know. (a bad server supporting SSLv3 to TLS 1.2 costs 1-3 seconds). 

Three minor points:
* The sequence of TLS 1.2 and TLS 1.3  sig_algs offered should be rather low  to high number.
* _nonsense deleted ;-)_
* In one case I had encountered an empty line for TLS 1.2 sig_algs

image

I am just trying to figure out why

**Comment by dcooper16** [comment]
Hi Dirk,

I reversed the order of the output for TLS 1.2 and TLS 1.3.

I haven't been able to find a server that shows an empty list of signature algorithms for TLS 1.2, but with some additional testing I found 2 server that show an empty list for TLS 1.3. In both cases the server seems to be returning a CertificateVerify message where the SignatureScheme if 0xFFFF. Since testssl.sh doesn't recognize this value, it just stops the testing for supported signature algorithms.

So far, I have not been able to find anything to suggest that testssl.sh is not correctly decrypting or parsing the CertificateVerify message, and I haven't found anything to explain how 0xFFFF could be an acceptable value. So, I do not know what is happening.

It may be the case with the server you tested that the SignatureAndHashAlgorithm specified in the ServerKeyExchange is unrecognized, but I would need to see the server's response to know whether that is the case.

**Comment by dcooper16** [comment]
For the servers that were returning a SignatureScheme of 0xFFFF for TLS 1.3, the problem seems to occur if the signature_algorithms extension includes too many signature schemes. So, I added a commit that breaks the list of signature schemes in two and tries each list separately. This seems to fix the problem.

I don't know whether the same problem happens with some servers with TLS 1.2, but I reduced the size of the signature_algorithms extension for TLS 1.2 as well. For TLS 1.2 this simply involved generally not including values that were inconsistent with the key type being tested. For example, if the cipher suite being offered requires the server to use an RSA key, there is no reason for the signature_algorithms extension to offer signature schemes that require the use of a DSA or ECDSA key.

**Comment by drwetter** [comment]
Hi David, thanks a lot!

yeah, it's a bit faster now. Other than that I can't see whether there's more time we can save now.

For next development stage I was thinking about saving all reusable information we got from far in memory like e.g. we already did regarding protocols (maybe better, I did that a bit too clunky to handle). That may save one or another handshake.

**Comment by teki69** [comment]
Hello,
I have a TLS 1.2 server supporting PFS ciphers, and yet "TLS 1.2 sig_algs offered" is showing empty :

2024-12-20 19_51_25-Clipboard

I'm using testssl 3.2rc3.
Would you like me to send you the report or its public IP in a private message ?

Best regard

**Comment by drwetter** [comment]
yes pls. ``grep SWCONTACT testssl.sh``

**Comment by drwetter** [comment]
Best is to open a separate issue , @teki69 . Otherwise this might get lost. Just a link on your message here is fine

**Pull request merged**
