### PR TITLE
Improved support for servers using client certificate authentication

### PR DESCRIPTION
**Pull request by Iansus**
When using **client certificates**, openssl returns exit code 1 since the handshake is not successful.
However, that does not prevent this tool from listing ciphers & searching for vulnerabilities.

### CODE REVIEW

**Comment by Iansus** [comment]
Pull request was made a bit too soon, it still needs some corrections.

**Comment by drwetter** [comment]
It has to be a unique string/strings. E.g.Tried that a bit already but did not get to the end.

Hints

```
[[ -z $(awk '/Master-Key: / { print $2 }' "$1") ]] 
[[ -n $(awk '/Session-ID: / { print $2 }' "$1") ]]
[[ 2 -eq $(grep -ac CERTIFICATE "$1" ) ]]

```

**Comment by Iansus** [comment]
Well I think "Cipher is " should work, except the "NONE" case.
At least it does in my tests. The corrections were about logic flaws I
introduced in the pull requests.

Great tool anyhow !

**Comment by drwetter** [comment]
Am 29. September 2015 19:12:38 MESZ, schrieb Iansus <notifications@github.com>:
>Well I think "Cipher is " should work, except the "NONE" case.
>At least it does in my tests. The corrections were about logic flaws I
>introduced in the pull requests.
>
>Great tool anyhow !
>Le 29 sept. 2015 6:57 PM, "Dirk Wetter" <notifications@github.com> a
>écrit :
>
>> It has to be a unique string/strings. E.g.Tried that a bit already
>but did
>> not get to the end.
>>
>> Hints
>>
>> [[ -z $(awk '/Master-Key: / { print $2 }' "$1") ]]
>> [[ -n $(awk '/Session-ID: / { print $2 }' "$1") ]]
>> [[ 2 -eq $(grep -ac CERTIFICATE "$1" ) ]]
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/drwetter/testssl.sh/pull/206#issuecomment-144119933>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/pull/206#issuecomment-144124410

As I tested it it was not 100% reliable. Keep in mind that people use strange openssl versions or have strange server side ssl stacks.

It's THE  core check  thus we need 100%.

Cheers, Dirk!




-- 
Sent from my mobile

**Comment by drwetter** [comment]
Hi @Iansus ,

FYI: I have something in the works. As workaday life permits I'll finish that and commit it.

Cheers, Dirk

**Comment by drwetter** [comment]
Every s_client connect call is now differently judged for success. A function is used:

```
sclient_connect_successful() {
     [[ $1 -eq 0 ]] && return 0
     [[ -z $(awk '/Master-Key: / { print $2 }' "$2") ]] && return 1
     [[ -z $(awk '/Session-ID: / { print $2 }' "$2") ]] && return 1
     # what's left now is: master key not empty and Session-ID not empty ==> probably client based auth with x509 certificate
     CLIENT_AUTH=true
     return 0
}
```
The function is called with ``sclient_connect_successful $? $TMPFILE``. That should be not much of a speed disadvantage, Maybe one of the check will vanish. But that needs to be proved by intensive tests.

I've done a lot of tests on regular hosts it and it worked (but needed some polishing the first two drafts).

I have not tested it much on hosts needed a certificate, @Iansus maybe you can give it a shot?

Cheers, Dirk

**Comment by Iansus** [comment]
I'll check that ;)

**Comment by drwetter** [comment]
cool!

**Pull request closed without merging**
