### PR TITLE
Fix #1514

### LINKED ISSUE #1514: Race condition in JSON pretty print during batch testing.
When doing parallel testing with a big number of host names (> 1000) involving multiple time consuming tests (see below), sometimes after the JSON file is actually finalized additional results are appended to the file rendering it invalid!

1. uname -a
   `Darwin hampers.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`

2. testssl version from the banner: testssl.sh -b 2>/dev/null | head -4 | tail -2
  ```
  testssl.sh       3.1dev fromhttps://testssl.sh/dev/
    (64fea03 2020-02-15 15:22:22 -- )
   ```

3. git log | head -1 (if running from git repo)
  `commit 64fea03f665bed7b03bbc217496f63ee93a26b19`

4. openssl version used by testssl.sh: testssl.sh -b 2>/dev/null | awk -F':' '/openssl/ { print $2}'
  `Using "OpenSSL 1.0.2-chacha (1.0.2k-dev)" [~183 ciphers]`

5. steps to reproduce: testssl.sh or docker command line, if possible incl. host
 ```bash
testssl.sh \
  --cipher-per-proto \
  --grease \
  --server-defaults \
  --server-preference \
  --vulnerable \
  --pfs \
  --assume-http \
  --parallel \
  --file $DOMAIN_LIST \
  --jsonfile-pretty $TARGET_DIR
```

6. what exactly was happening, output is needed
In a sample of > 1K domains at least ~10% produce invalid JSON by appending residual test results to the finalized JSON file such as the following (excerpts only):

```json
"cipherTests"       : [

                    ]
          }
          ],
                    "scanTime"  : 633
}
                            {
                                "id"           : "cipher-tls1_xc013",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   xc013   ECDHE-RSA-AES128-SHA              ECDH 256   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x2f",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "repeated openssl s_client connect problem, doesn't make sense to continue"
                           }
```

or 

```json
"cipherTests"       : [
                            {
                                "id"           : "cipher-tls1_xc014",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   xc014   ECDHE-RSA-AES256-SHA              ECDH 256   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x39",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x39     DHE-RSA-AES256-SHA                DH 1024    AES         256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x35",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_xc013",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   xc013   ECDHE-RSA-AES128-SHA              ECDH 256   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x33",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x33     DHE-RSA-AES128-SHA                DH 1024    AES         128      TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x2f",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_x05",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x05     RC4-SHA                           RSA        RC4         128      TLS_RSA_WITH_RC4_128_SHA"
                           },{
                                "id"           : "cipher-tls1_x04",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x04     RC4-MD5                           RSA        RC4         128      TLS_RSA_WITH_RC4_128_MD5"
                           },{
                                "id"           : "cipher-tls1_x0a",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1   x0a     DES-CBC3-SHA                      RSA        3DES        168      TLS_RSA_WITH_3DES_EDE_CBC_SHA"
                           }
                    ]
          }
          ],
                    "scanTime"  : "Scan interrupted"
}
,{
                                "id"           : "cipher-tls1_1_xc014",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   xc014   ECDHE-RSA-AES256-SHA              ECDH 256   AES         256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x39",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x39     DHE-RSA-AES256-SHA                DH 1024    AES         256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x35",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x35     AES256-SHA                        RSA        AES         256      TLS_RSA_WITH_AES_256_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_xc013",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   xc013   ECDHE-RSA-AES128-SHA              ECDH 256   AES         128      TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x33",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x33     DHE-RSA-AES128-SHA                DH 1024    AES         128      TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x2f",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x2f     AES128-SHA                        RSA        AES         128      TLS_RSA_WITH_AES_128_CBC_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x05",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x05     RC4-SHA                           RSA        RC4         128      TLS_RSA_WITH_RC4_128_SHA"
                           },{
                                "id"           : "cipher-tls1_1_x04",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x04     RC4-MD5                           RSA        RC4         128      TLS_RSA_WITH_RC4_128_MD5"
                           },{
                                "id"           : "cipher-tls1_1_x0a",
                                "severity"     : "INFO",
                                "finding"      : "TLS 1.1   x0a     DES-CBC3-SHA                      RSA        3DES        168      TLS_RSA_WITH_3DES_EDE_CBC_SHA"
                           },{
                                "id"           : "scanProblem",
                                "severity"     : "FATAL",
                                "finding"      : "repeated openssl s_client connect problem, doesn't make sense to continue"
                           }
```

As you can see, in the former example what should have been inside the `cipherTests` is printed after the JSON file is closed and in the latter case after the test is interrupted some residual results are appended to the file.

---

**Note:** I observed this behavior *after* adding extra tests (i.e., `--grease`, `--server-defaults`, and`--server-preference`, however, I cannot be sure if this is the reason as files are all valid when testing single hosts.

You can take a look at some examples where this happens [here](https://gist.github.com/yan-foto/98cac8d7ee6cbdef34258cf7976b2c22).

### PR DESCRIPTION
**Pull request by dcooper16**
This PR is an attempt to fix #1514. The PR is mostly based on a suggestion at https://unix.stackexchange.com/questions/57940/trap-int-term-exit-really-necessary. Even with that change, it seemed that if testssl.sh were in the middle of executing `run_cipher_per_proto()` when it received a signal, it would not stop until that function had completed. This seems to have something to do with subshells. Changing the while loop in `run_cipher_per_proto()` seems to have fixed that issue. So, I also made similar changes to the while loops in `prettyprint_local()`.

While this PR seems to fix the problem, I can't say that I fully understand the changes that I've made. So, it should definitely be tested some more before it is merged.

### CODE REVIEW

**Comment by drwetter** [comment]
Thanks, David!

@yan-foto: Your turn, please ;-)

**Comment by yan-foto** [comment]
@drwetter I'll rerun my tests tonight and will let you know if the problem is solve! You should, however, note that this would not be an adequate replacement for systematic testing 😄

**Comment by yan-foto** [comment]
I ran my batch tests three times and every time the execution halts after 100 to 200 iterations (out of expected > 1000 hosts in the list). It seems that even though some tests time out, `testssl.sh` does not recognize that these have failed and new tests can be spawned.

I am not sure how to proceed with debugging from here!

**Comment by drwetter** [comment]
Am 7. März 2020 18:43:10 MEZ schrieb Yan Foto <notifications@github.com>:
>I ran my batch tests three times and every time the execution halts
>after 100 to 200 iterations (out of expected > 1000 hosts in the list).

Haven't seen that myself in previous versions. Are those the same hosts every run?

>It seems that even though some tests time out, `testssl.sh` does not
>recognize that these have failed and new tests can be spawned.

So you mean they weren't spawned?

>I am not sure how to proceed with debugging from here!

See David's comment above with bash -x, if you want to go deeper


-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by yan-foto** [comment]
> Haven't seen that myself in previous versions. Are those the same hosts every run?

yes!

> So you mean they weren't spawned?

No! I can also verify this in `top` and `ps`.

> See David's comment above with bash -x, if you want to go deeper

I might need time to try this one out.

**Comment by drwetter** [comment]
>>    Haven't seen that myself in previous versions. Are those the same hosts every run?
>
> yes!

Are they getting stuck in a single run too?

**Comment by yan-foto** [comment]
> Are they getting stuck in a single run too?

No. Interesting thing is that it doesn't get stuck always on the same host.

**Comment by dcooper16** [comment]
So far I have not been able to repeat this. I tried a test that involved several hundred hosts, and I set MAX_WAIT_TEST to 30 so that every single test timed out. The parent testssl.sh process continued to time out and kill older tests and start new tests.

I also checked and none of the JSON files that were created included anything after the "scanTime" entry, so I wasn't seeing any instances of the original problem (from #1514).

The default value for MAX_WAIT_TEST is 1200, which should be far longer than it typically takes to run a test. If tests for a lot of hosts are timing out when running parallel tests, but they are not timing out when running the tests one at a time, perhaps part of the problem is that your client is just overloaded. I know that when I perform parallel testing, each of the individual tests runs more slowly, since my desktop gets a bit overloaded trying to run 20 tests at the same time.

You may want to try setting MAX_PARALLEL something smaller than 20 (maybe 5 or 10). This won't answer the question of why the parent testssl.sh process is stopping before it has gone through all of the hosts. However, if your system is slowing to a crawl and tests are timing out because the client is trying to run too many tests at the same time, testing may run better if MAX_PARALLEL is smaller so that your client doesn't try to do too many things at the same time.

**Comment by yan-foto** [comment]
I have been meaning to run new tests but due to the current situation I don't have a stable Internet connection and cannot do proper testing.

**Comment by drwetter** [comment]
Thanks, @dcooper16 .  

@yan-foto : I merged this, hoping it resolves your issue. If you'll be able to check at some point of time, please let us know - one way or the other.

Cheers, Dirk

**Pull request merged**
