### PR TITLE
OS X builds with as many ciphers as possible without generating errors. Should fix #127

### LINKED ISSUE #127: Supply Darwin binaries + install documentation
It would be awesome if somebody could contribute OS X binaries from @PeterMosmans OpenSSL fork and also document the installation (sorry, I am a Mac n00b)

### PR DESCRIPTION
**Pull request by jpluimers**
OS X builds with 
cc_arguments_common="no-shared enable-static-engine no-zlib-dynamic enable-zlib enable-ssl2 enable-ssl3 enable-ssl-trace enable-rc2 enable-rc5 enable-gost enable-cms enable-md2 enable-mdc2 enable-ec enable-ec2m enable-ecdh enable-ecdsa enable-seed enable-camellia enable-idea enable-rfc3779 experimental-jpake -DOPENSSL_USE_BUILD_DATE"
   cc_arguments_x86="$cc_arguments_common"
   cc_arguments_x64="$cc_arguments_common enable-ec_nistp_64_gcc_128 "
Note: no -DTEMP_GOST_TLS yet. Will need to resolve some errors in the tests.
Test-logs: https://gist.github.com/jpluimers/6ff5362eb8a7327f2ba5

### CODE REVIEW

**Comment by drwetter** [comment]
Hi @jpluimers,

sounds awesome! Could you do a  ``openssl ciphers -V 'ALL:COMPLEMENTOFALL' | wc -l``?

Cheers, Dirk

**Comment by jpluimers** [comment]
See the build logs here: https://gist.github.com/jpluimers/b0196409a3df78187295

**Comment by drwetter** [comment]
Thx!
~~It's one more I have (if I compile without `` -DTEMP_GOST_TLS``)~~ you counted the line ``WARNING: can't open config file: /usr/local/ssl/openssl.cnf`` ;-)

**Comment by drwetter** [comment]
So same baseline, thx!

**Pull request merged**
