### PR TITLE
Missing HTML banner

### PR DESCRIPTION
**Pull request by dcooper16**
With the commit made on March 26, "partly (1/2) fixing #653," an HTML banner isn't added to the HTML files anymore.  A banner should be added to the top of the HTML file if mass testing is being performed and a separate HTML file is being created for each test.

The `$APPEND` flag being `true` is an indicator that mass testing is being performed and that this is one of the individual tests being run. Given that `$APPEND` is `true`, `$HTMLHEADER` being `true` indicates that testssl.sh is creating the file name for the HTML output. So, it is when both flags are `true` that the HTML banner should be created.

### CODE REVIEW

**Comment by drwetter** [comment]
> With the commit made on March 26, "partly (1/2) fixing #653," an HTML banner isn't added to the HTML files anymore

IIRC there wasn't a banner at all before in the scenarios I tested but it seems I tested something I can't remember (and reproduce).  

General Q: Why should a banner depend on file append?

My impression as I closed the laptop that night was rather that ``--append`` needs to be reconsidered. ``run_mass_testing()`` has for historical reasons I forgot ``cmdline="$0 $global_cmdline --warnings=batch -q --append $cmdline"``. If there's a single file that makes sense but only then, right?

**Comment by drwetter** [comment]
Shouldn't there be always an HTML banner? If so I would just recommend removing ``$APPEND`` completely, That's at least how I redid the JSON part, see ``fileout_banner()``

**Comment by drwetter** [comment]
For the time being your PR indeed fixes it. With the release of this version that should be changed, see #684 .

**Comment by dcooper16** [comment]
> Shouldn't there be always an HTML banner? If so I would just recommend removing $APPEND completely, That's at least how I redid the JSON part, see fileout_banner()

Actually, the JSON file doesn't always have a banner. The main body of testssl.sh is as follows:
```
if $do_mass_testing; then
     prepare_logging
     run_mass_testing
     exit $?
fi

html_banner
fileout_banner
```

So, in the case of mass testing, `fileout_banner()` is only called by the "children." If `--jsonfile-pretty` is used instead of `json-pretty`, then `$JSONHEADER` will be set to `false` in the "children," so none of them will call `fileout_pretty_json_banner()` (which they shouldn't). So, in the case of an invocation like
```
bash testssl.sh --jsonfile-pretty out.json --file serverstotest.txt
```
no banner will be included in out.json.

**Pull request merged**
