### PR TITLE
Add JSON and CSV output to testssl.sh

### PR DESCRIPTION
**Pull request by seccubus**
@drwetter ,

This is how I intend to add JSON output to ssl test so it can be used by other tools. Does this seem like to correct way to do it?

Please let me know.

P.S. Don't merge this pull request yet, it is work in progress.
P.P.S. It's done now.

### CODE REVIEW

**Comment by seccubus** [comment]
Can I take that as a "yes, that is the way to do it, please continue" ?

**Comment by drwetter** [comment]
yes, absolutely!

One incy wincy thing pls upfront:  s/output_finding/json_out/ .

**Comment by seccubus** [comment]
Deliberatly didn't do that. If you have this hook in place it should be relatively easy to make csv output al well by adding csv output to the output_finding function.

Sent from my mobile device, sorry for the typyos.

On 10 Dec 2015, at 11:18, Dirk Wetter <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, absolutely!

One incy wincy thing pls upfront: s/output_finding/json_out/ .

**Comment by drwetter** [comment]
ah, ok.

**Comment by seccubus** [comment]
@drwetter please process this pull request. If possible can you bump  the version number so downstream tools can test if your script supports json/csv output?

**Comment by seccubus** [comment]
Want me to fix the backticks first @drwetter ?
If you approve this PR before #259 there shouldn't be a problem.

**Pull request closed without merging**
