### PR TITLE
Add wiresharked Android 7.0 (native)

### PR DESCRIPTION
**Pull request by csett86**
After being bitten by https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0
I add a wiresharked Android 7.0 to reflect that bug in Android 7.0.

### CODE REVIEW

**Comment by typingArtist** [comment]
See also #540.

**Comment by drwetter** [comment]
Ok, thanks. What app / did you use?

And: you're sure you want to leave the server name in there?

**Comment by csett86** [comment]
I used RiotX (which uses Android system libraries and thus was no longer working just on Android 7.0 once our hoster switched to EC P-384 certificates) and the server name is fine in there, its a public service operated by myself.

**Comment by drwetter** [comment]
Ok, thank you!

Do you mind handing in a PR for the 3.0 branch as well?

**Comment by csett86** [comment]
PR for 3.0 here: #1661

**Pull request merged**
