### PR TITLE
Added a check for TLS_FALLBACK_SCSV

### PR DESCRIPTION
**Pull request by JonnyHightower**
Hi Dirk,

I've added a check for TLS_FALLBACK_SCSV support on the server. I bumped the version number of the script to 2.6dev - wasn't sure what else to do with it sorry, so ignore if you like!

Cheers,
Jon

### CODE REVIEW

**Comment by drwetter** [comment]
Thx, cool!  Bear with me a bit pls.  

Or -- if you don't  mind: The check for the availabilty of the openssl option is missing (if not --> pr_litemagenta "Local problem> ...." ).

The version is 2.5dev. Even numbes: stable. Odd=devel

**Comment by drwetter** [comment]
see also #22 btw

**Comment by JonnyHightower** [comment]
Sorry Dirk - that was my first ever pull request. I hadn't noticed #22 sorry. I'll make the appropriate changes.

**Comment by drwetter** [comment]
no need for excuses, @JonnyHightower. ;-) Glad that someone contributes. 

Gimme a bit.

**Comment by JonnyHightower** [comment]
No rush Dirk. Thanks for making such a great tool publicly available :)

**Comment by drwetter** [comment]
Thank you, @JonnyHightower . Much appreciated!

**Pull request merged**
