### PR TITLE
Added check for certificate validity longer than 398 days

### PR DESCRIPTION
**Pull request by tosticated**
Added check for certificate validity longer than 398 days as more browsers and CA's are implementing this. See for example: https://blog.mozilla.org/security/2020/07/09/reducing-tls-certificate-lifespans-to-398-days/

Copied and modified from the existing check for 825 days validity.

### CODE REVIEW

**Comment by drwetter** [comment]
Hi @tosticated ,

thanks a lot for the PR and sorry for letting this sit here.

Code and implementation looks great. You mind to add this to ``CHANGELOG.md``` and if you like to the ``CREDITS.md``?
Then I'll merge it ASAP.

Cheers, Dirk

**Comment by drwetter** [comment]
Thanks!

**Comment by tosticated** [comment]
Hi @drwetter ,

Thank you for accepting the PR and reminding me to update the changelog and credits file. Changes have been committed, feel free to merge when you want.

Thanks, @tosticated

**Comment by drwetter** [comment]
already done

**Pull request merged**
