### PR TITLE
Don't include SEED in PFS

### PR DESCRIPTION
**Pull request by dcooper16**
`run_pfs()` is only supposed to test for "robust" (P)FS ciphers. For this reason, ciphers that use 3DES are not included. Given that `pr_cipher_quality()` rates SEED the same as 3DES (`pr_svrty_medium`), it would seem that SEED ciphers should not be included either.

`pr_cipher_quality()` also rates IDEA ciphers as `pr_svrty_medium`, but there are no (P)FS cipher suites that use IDEA.

`run_pfs()` still includes cipher suites that are rated by `pr_cipher_quality()` as `pr_svrty_low` -- the ciphers that use CBC padding.

### CODE REVIEW

**Comment by dcooper16** [comment]
On a somewhat related note, there is a [discussion](https://mailarchive.ietf.org/arch/msg/saag/ob6Hn6AlD8RW7RpXeBHF1fzCed4/) in the IETF about whether the property should be called "perfect forward secrecy" or just "forward secrecy."

It seems the people generally think it's okay to use either term, but think that "forward secrecy" is a bit better. Eric Rescorla noted that there was an explicit decision to use "forward secret" rather than "perfect forward secret" in RFC 8446.

**Comment by drwetter** [comment]
yeah, FS is better.

Jon Callas: "Forward secrecy is a much better term. Saying "perfect" forward secrecy is kinda like "military-grade" encryption in the way it's misused, and often a shibboleth showing trying to puff things up." 

:-)

With the quantum computing more or less beyond the horizon the attribute "perfect" sounds strange.

**Comment by drwetter** [comment]
Hi David,

thanks.

But maybe you can describe your (cryptography wise) problem with SEED or: where should we draw the line for ciphers to be included?

My idea of the FS section was to focus on the key exchange, then to weed out any weak encryption. I am with you regarding also throwing out the medium ciphers as well. But our stances seems different wrt medium. See also discussion @ #1157.

Cheers, Dirk

**Comment by dcooper16** [comment]
> But maybe you can describe your (cryptography wise) problem with SEED or: where should we draw the line for ciphers to be included?
> 
> My idea of the FS section was to focus on the key exchange, then to weed out any weak encryption. I am with you regarding also throwing out the medium ciphers as well. But our stances seems different wrt medium. See also discussion @ #1157.

Okay, it seems that I submitted the wrong PR. I just ran a test with COLOR=3 and saw that the SEED cipher was listed in a warning color. The color is determined by `pr_cipher_quality`, and when I saw that `pr_cipher_quality` rates 3DES, IDEA, and SEED ciphers the same, I thought that since 3DES ciphers are not considered "robust," SEED ciphers shouldn't be considered "robust" either.

According to #1157, however, it seems that the problem is with `pr_cipher_quality` rather than `run_pfs`. I'll close this PR and work on a different one that tries to better align the ratings in `pr_cipher_quality` with those in `run_cipherlists`.

**Comment by drwetter** [comment]
> I'll close this PR and work on a different one that tries to better align the ratings in pr_cipher_quality(0 with those in run_cipherlists()

It seems in fact I missed SEED last year when I last tried to adjust both

**Pull request closed without merging**
