### PR TITLE
Dockerfile for testssl.sh

### PR DESCRIPTION
**Pull request by dr4y**
Added a Dockerfile for using testssl.sh with docker.

Usage:
docker run -t testssl.sh example.com

Ability to pull image from docker hub:
docker run -t dr4y/testssl.sh example.com

### CODE REVIEW

**Comment by drwetter** [comment]
@dr4y : have you looked into what @jumanjiman did?

Another thing to mention is that Debian is used and not Alpine Linux which is way smaller.

**Comment by jumanjiman** [comment]
@dr4y If you maintain your docker image as a separate repo similar to [1], it would be appropriate to suggest your repo within the readme [here](https://github.com/drwetter/testssl.sh#externalrelated-projects).

[1] https://github.com/jumanjihouse/docker-testssl

**Comment by drwetter** [comment]
As discussed in person Alpine would be great

**Comment by drwetter** [comment]
temporarily merge to get thing going

**Pull request merged**
