### PR TITLE
Add Java 11 and 12 client simulations

### PR DESCRIPTION
**Pull request by csett86**
manually wiresharked, this should close two more items from #1158.

### CODE REVIEW

**Comment by drwetter** [comment]
Hi @csett86 ,

thanks! There seems to be a problem with the new CI tests (I merged a couple of minutes before) and your PR.

--> Task for Monday+

Thx, Dirk

**Comment by drwetter** [comment]
Hi @csett86 ,

the CI test actually caught the mistake(s) of yours. Would you mind please to replace the space by a colon in front of DES-CBC-MD5?

Dirk

**Comment by csett86** [comment]
Hi Dirk,

that is even better, because the space (and DES-CBC-MD5) was inserted by utils/hexstream2cipher.sh, heres the relevant snippet:

148: c025 --> 0xc0,0x25 --> ECDH-ECDSA-AES128-SHA256
152: c029 --> 0xc0,0x29 --> ECDH-RSA-AES128-SHA256
156: 0067 --> 0x00,0x67 --> DHE-RSA-AES128-SHA256
160: 0040 --> 0x00,0x40 --> DHE-DSS-AES128-SHA256 DES-CBC-MD5
164: c009 --> 0xc0,0x09 --> ECDHE-ECDSA-AES128-SHA
168: c013 --> 0xc0,0x13 --> ECDHE-RSA-AES128-SHA
172: 002f --> 0x00,0x2f --> AES128-SHA
176: c004 --> 0xc0,0x04 --> ECDH-ECDSA-AES128-SHA

Unfortunately I don't know how to fix utils/hexstream2cipher.sh, but I have manually removed the erroneous cipher and space from the client-sim.

Kind regards,
Christoph

**Comment by drwetter** [comment]
Hi Christoph,

hmm, I never saw this but happy to fix utils/hexstream2cipher.sh .

But it Looks to me you marked the whole SSL hello as the cipher numbers
(148, 152) seem rather strange. Documentation says

For "ciphers" mark the Cipher Suites --> Copy --> As a hex stream, remove any leading GREASE ciphers (?a?a) and supply it to ~/utils/hexstream2cipher.sh

If I do this It looks like

# ciphers: 18
00: 1301 --> 0x13,0x01 --> TLS_AES_128_GCM_SHA256
04: 1303 --> 0x13,0x03 --> TLS_CHACHA20_POLY1305_SHA256
08: 1302 --> 0x13,0x02 --> TLS_AES_256_GCM_SHA384
12: c02b --> 0xc0,0x2b --> ECDHE-ECDSA-AES128-GCM-SHA256
16: c02f --> 0xc0,0x2f --> ECDHE-RSA-AES128-GCM-SHA256
20: cca9 --> 0xcc,0xa9 --> ECDHE-ECDSA-CHACHA20-POLY1305
24: cca8 --> 0xcc,0xa8 --> ECDHE-RSA-CHACHA20-POLY1305
28: c02c --> 0xc0,0x2c --> ECDHE-ECDSA-AES256-GCM-SHA384
32: c030 --> 0xc0,0x30 --> ECDHE-RSA-AES256-GCM-SHA384
36: c00a --> 0xc0,0x0a --> ECDHE-ECDSA-AES256-SHA
40: c009 --> 0xc0,0x09 --> ECDHE-ECDSA-AES128-SHA
44: c013 --> 0xc0,0x13 --> ECDHE-RSA-AES128-SHA
48: c014 --> 0xc0,0x14 --> ECDHE-RSA-AES256-SHA
52: 0033 --> 0x00,0x33 --> DHE-RSA-AES128-SHA
56: 0039 --> 0x00,0x39 --> DHE-RSA-AES256-SHA
60: 002f --> 0x00,0x2f --> AES128-SHA
64: 0035 --> 0x00,0x35 --> AES256-SHA
68: 000a --> 0x00,0x0a --> DES-CBC3-SHA

TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384


Please double check Safari too as other people rely on your data.

Cheers, Dirk

**Comment by csett86** [comment]
Hi Dirk,

I checked my Safari contrib and there everything works as expected and I also checked that I only supplied the cipher suites to hexstream2cipher.sh.

Taking Java 11 from this contrib as an example I re-checked and the problem looks reproducible:

Wireshark is reporting 44 ciphers, and when I select the Cipher Suites -> Copy -> Bytes as hexstream and supply that to hexstream2cipher.sh, I get:

$ ./utils/hexstream2cipher.sh 13011302c02cc02bc030009dc02ec032009f00a3c02f009cc02dc031009e00a2c024c028003dc026c02a006b006ac00ac0140035c005c00f00390038c023c027003cc025c02900670040c009c013002fc004c00e00330032
# ciphers: 44
00: 1301 --> 0x13,0x01 --> TLS_AES_128_GCM_SHA256
04: 1302 --> 0x13,0x02 --> TLS_AES_256_GCM_SHA384
08: c02c --> 0xc0,0x2c --> ECDHE-ECDSA-AES256-GCM-SHA384
12: c02b --> 0xc0,0x2b --> ECDHE-ECDSA-AES128-GCM-SHA256
16: c030 --> 0xc0,0x30 --> ECDHE-RSA-AES256-GCM-SHA384
20: 009d --> 0x00,0x9d --> AES256-GCM-SHA384
24: c02e --> 0xc0,0x2e --> ECDH-ECDSA-AES256-GCM-SHA384
28: c032 --> 0xc0,0x32 --> ECDH-RSA-AES256-GCM-SHA384
32: 009f --> 0x00,0x9f --> DHE-RSA-AES256-GCM-SHA384
36: 00a3 --> 0x00,0xa3 --> DHE-DSS-AES256-GCM-SHA384
40: c02f --> 0xc0,0x2f --> ECDHE-RSA-AES128-GCM-SHA256
44: 009c --> 0x00,0x9c --> AES128-GCM-SHA256
48: c02d --> 0xc0,0x2d --> ECDH-ECDSA-AES128-GCM-SHA256
52: c031 --> 0xc0,0x31 --> ECDH-RSA-AES128-GCM-SHA256
56: 009e --> 0x00,0x9e --> DHE-RSA-AES128-GCM-SHA256
60: 00a2 --> 0x00,0xa2 --> DHE-DSS-AES128-GCM-SHA256
64: c024 --> 0xc0,0x24 --> ECDHE-ECDSA-AES256-SHA384
68: c028 --> 0xc0,0x28 --> ECDHE-RSA-AES256-SHA384
72: 003d --> 0x00,0x3d --> AES256-SHA256
76: c026 --> 0xc0,0x26 --> ECDH-ECDSA-AES256-SHA384
80: c02a --> 0xc0,0x2a --> ECDH-RSA-AES256-SHA384
84: 006b --> 0x00,0x6b --> DHE-RSA-AES256-SHA256
88: 006a --> 0x00,0x6a --> DHE-DSS-AES256-SHA256
92: c00a --> 0xc0,0x0a --> ECDHE-ECDSA-AES256-SHA
96: c014 --> 0xc0,0x14 --> ECDHE-RSA-AES256-SHA
100: 0035 --> 0x00,0x35 --> AES256-SHA
104: c005 --> 0xc0,0x05 --> ECDH-ECDSA-AES256-SHA
108: c00f --> 0xc0,0x0f --> ECDH-RSA-AES256-SHA
112: 0039 --> 0x00,0x39 --> DHE-RSA-AES256-SHA
116: 0038 --> 0x00,0x38 --> DHE-DSS-AES256-SHA
120: c023 --> 0xc0,0x23 --> ECDHE-ECDSA-AES128-SHA256
124: c027 --> 0xc0,0x27 --> ECDHE-RSA-AES128-SHA256
128: 003c --> 0x00,0x3c --> AES128-SHA256
132: c025 --> 0xc0,0x25 --> ECDH-ECDSA-AES128-SHA256
136: c029 --> 0xc0,0x29 --> ECDH-RSA-AES128-SHA256
140: 0067 --> 0x00,0x67 --> DHE-RSA-AES128-SHA256
144: 0040 --> 0x00,0x40 --> DHE-DSS-AES128-SHA256 DES-CBC-MD5
148: c009 --> 0xc0,0x09 --> ECDHE-ECDSA-AES128-SHA
152: c013 --> 0xc0,0x13 --> ECDHE-RSA-AES128-SHA
156: 002f --> 0x00,0x2f --> AES128-SHA
160: c004 --> 0xc0,0x04 --> ECDH-ECDSA-AES128-SHA
164: c00e --> 0xc0,0x0e --> ECDH-RSA-AES128-SHA
168: 0033 --> 0x00,0x33 --> DHE-RSA-AES128-SHA
172: 0032 --> 0x00,0x32 --> DHE-DSS-AES128-SHA

TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:AES256-GCM-SHA384:ECDH-ECDSA-AES256-GCM-SHA384:ECDH-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:AES128-GCM-SHA256:ECDH-ECDSA-AES128-GCM-SHA256:ECDH-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:AES256-SHA256:ECDH-ECDSA-AES256-SHA384:ECDH-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:AES256-SHA:ECDH-ECDSA-AES256-SHA:ECDH-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:AES128-SHA256:ECDH-ECDSA-AES128-SHA256:ECDH-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:DHE-DSS-AES128-SHA256 DES-CBC-MD5:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:AES128-SHA:ECDH-ECDSA-AES128-SHA:ECDH-RSA-AES128-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA

To me this looks like 44 cipher suites but in byte 144 the util adds a space and DES-CBC-MD5 at the end to the valid DHE-DSS-AES128-SHA256.

What do you think?

Kind regards,
Christoph

**Comment by drwetter** [comment]
Ah, that wasn't a full quote before, sorry. Hold on..

**Comment by drwetter** [comment]
Thanks!

**Comment by drwetter** [comment]
I'd like to change Ubuntu to something less specific as I assume OpenJDK should serve the same handshake on other OS, unless manually configured differently.

I guess 19.04 has also OpenJDK, right?

**Comment by csett86** [comment]
Yes this is both OpenJDK, the detailed version info is in the commit messages of c4b5f3353212efe16fbd1e16491db7dbc3fb2772 and 11416790cd691382a75776dfb417b5dc9fc3cf78

I was unsure what to put into the brackets either so I took Ubuntu (as in the openssl case, but there it makes a lot more sense...)

Do you think Java 10 is still necessary? Support for it has already ended in September 2018. And I guess Java 9 can now be removed as well, as its support has ended in March 2018 as well. Both according to https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by drwetter** [comment]
If you have a Java 10 version handy another PR would be appreciated despite it's EOL.

Probably this and v9 should be not current=true anymore -- unless anybody objects (don't know whether some distros still provide support).

-- 
Sent from my mobile. Excuse my brevity&typos+the phone's autocorrection

**Comment by csett86** [comment]
Unfortunately I don't have Java 10 handy, and I could not find any disto supporting it either, checked Ubuntu, Debian, Fedora...

Deprecation pull for Java 9 coming.

**Pull request merged**
