### PR TITLE
Feature/client sims

### PR DESCRIPTION
**Pull request by seccubus**
New feature for testssl.sh, client simulation, try to determine which client will negotiate which protocol and cipher.

### CODE REVIEW

**Comment by seccubus** [comment]
I know, that's what fired the inspiration particle in the first place. Once that feature is implemented we might even go for a tighter integration.

**Comment by drwetter** [comment]
very cool!, thx! Merging.

**Comment by drwetter** [comment]
@seccubus: For the openssl 1.0.2 client: What does "Tests are based on OpenSSL 1.01, therefore ciphers 0xe and 0xb are missing" mean?

**Comment by seccubus** [comment]
I mistakingly tought the version bundled with testssl.sh was the 1.0.1. version , it isn't:

$ bin/openssl.Darwin.x86_64 version
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
OpenSSL 1.0.2-chacha (1.0.2e-dev)

When I look at the list in SSL Labs I see that OpenSSL 1.0.2 offers two ciphers I don't have in the local version: https://www.ssllabs.com/ssltest/viewClient.html?name=OpenSSL&version=1.0.2

TLS_DH_RSA_EXPORT_WITH_DES40_CBC_SHA (0xe)   INSECURE	40
TLS_DH_DSS_EXPORT_WITH_DES40_CBC_SHA (0xb)   INSECURE	40

If I look at the list of ciphers offered by my local opsenssl instance I don't see theses ciphers there:

$ bin/openssl.Darwin.x86_64 ciphers -V|grep 0e
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
$ bin/openssl.Darwin.x86_64 ciphers -V|grep 0b
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
$

The warning that ciphers 0xe and 0xb are missing is correct, the reason that they are missing is incorrect (somehow)

**Comment by teward** [comment]
@seccubus That's an OpenSSL default - to see *all* ciphers available in any given OpenSSL, use `openssl ciphers -V "ALL:SUBSETOFALL"`.

From the static-built binaries that ship with testssl.sh:

```
% openssl_1.0.2 ciphers -V | grep export 
{ No Output }
% openssl_1.0.2 ciphers -V "ALL:SUBSETOFALL" | grep export
          0x00,0x63 - EXP1024-DHE-DSS-DES-CBC-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=DES(56)   Mac=SHA1 export
          0x00,0x62 - EXP1024-DES-CBC-SHA     SSLv3 Kx=RSA(1024) Au=RSA  Enc=DES(56)   Mac=SHA1 export
          0x00,0x61 - EXP1024-RC2-CBC-MD5     SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC2(56)   Mac=MD5  export
          0x00,0x65 - EXP1024-DHE-DSS-RC4-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x64 - EXP1024-RC4-SHA         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x60 - EXP1024-RC4-MD5         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=MD5  export
          0x00,0x14 - EXP-EDH-RSA-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x11 - EXP-EDH-DSS-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=DSS  Enc=DES(40)   Mac=SHA1 export
          0x00,0x19 - EXP-ADH-DES-CBC-SHA     SSLv3 Kx=DH(512)  Au=None Enc=DES(40)   Mac=SHA1 export
          0x00,0x08 - EXP-DES-CBC-SHA         SSLv3 Kx=RSA(512) Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x06 - EXP-RC2-CBC-MD5         SSLv3 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
     0x04,0x00,0x80 - EXP-RC2-CBC-MD5         SSLv2 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
          0x00,0x27 - EXP-KRB5-RC2-CBC-SHA    SSLv3 Kx=KRB5     Au=KRB5 Enc=RC2(40)   Mac=SHA1 export
          0x00,0x26 - EXP-KRB5-DES-CBC-SHA    SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(40)   Mac=SHA1 export
          0x00,0x2A - EXP-KRB5-RC2-CBC-MD5    SSLv3 Kx=KRB5     Au=KRB5 Enc=RC2(40)   Mac=MD5  export
          0x00,0x29 - EXP-KRB5-DES-CBC-MD5    SSLv3 Kx=KRB5     Au=KRB5 Enc=DES(40)   Mac=MD5  export
          0x00,0x17 - EXP-ADH-RC4-MD5         SSLv3 Kx=DH(512)  Au=None Enc=RC4(40)   Mac=MD5  export
          0x00,0x03 - EXP-RC4-MD5             SSLv3 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
     0x02,0x00,0x80 - EXP-RC4-MD5             SSLv2 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
          0x00,0x28 - EXP-KRB5-RC4-SHA        SSLv3 Kx=KRB5     Au=KRB5 Enc=RC4(40)   Mac=SHA1 export
          0x00,0x2B - EXP-KRB5-RC4-MD5        SSLv3 Kx=KRB5     Au=KRB5 Enc=RC4(40)   Mac=MD5  export
```

**Comment by seccubus** [comment]
Even if I do that, I still don't get the 0x0e or 0x0b cipher...

$ bin/openssl.Darwin.x86_64 ciphers -V 'ALL:COMPLEMENTOFALL:SUBSETOFALL:@STRENGTH'|grep -i export
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
          0x00,0x63 - EXP1024-DHE-DSS-DES-CBC-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=DES(56)   Mac=SHA1 export
          0x00,0x62 - EXP1024-DES-CBC-SHA     SSLv3 Kx=RSA(1024) Au=RSA  Enc=DES(56)   Mac=SHA1 export
          0x00,0x61 - EXP1024-RC2-CBC-MD5     SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC2(56)   Mac=MD5  export
          0x00,0x65 - EXP1024-DHE-DSS-RC4-SHA SSLv3 Kx=DH(1024) Au=DSS  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x64 - EXP1024-RC4-SHA         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=SHA1 export
          0x00,0x60 - EXP1024-RC4-MD5         SSLv3 Kx=RSA(1024) Au=RSA  Enc=RC4(56)   Mac=MD5  export
          0x00,0x14 - EXP-EDH-RSA-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x11 - EXP-EDH-DSS-DES-CBC-SHA SSLv3 Kx=DH(512)  Au=DSS  Enc=DES(40)   Mac=SHA1 export
          0x00,0x19 - EXP-ADH-DES-CBC-SHA     SSLv3 Kx=DH(512)  Au=None Enc=DES(40)   Mac=SHA1 export
          0x00,0x08 - EXP-DES-CBC-SHA         SSLv3 Kx=RSA(512) Au=RSA  Enc=DES(40)   Mac=SHA1 export
          0x00,0x06 - EXP-RC2-CBC-MD5         SSLv3 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
     0x04,0x00,0x80 - EXP-RC2-CBC-MD5         SSLv2 Kx=RSA(512) Au=RSA  Enc=RC2(40)   Mac=MD5  export
          0x00,0x17 - EXP-ADH-RC4-MD5         SSLv3 Kx=DH(512)  Au=None Enc=RC4(40)   Mac=MD5  export
          0x00,0x03 - EXP-RC4-MD5             SSLv3 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
     0x02,0x00,0x80 - EXP-RC4-MD5             SSLv2 Kx=RSA(512) Au=RSA  Enc=RC4(40)   Mac=MD5  export
     0x00,0x00,0x00 - NULL-MD5                SSLv2 Kx=RSA(512) Au=RSA  Enc=None      Mac=MD5  export

**Comment by teward** [comment]
That's interesting... I don't see those ciphers either, though I'm not entirely sure whether those ones were available in OpenSSL.  (I misspoke earlier)  Thought I did though...

**Comment by seccubus** [comment]
@teward I don't see those ciphers in your output either. Would you be able to pcap a connection with your openssl1.0.2 and sent the client hello?

**Comment by teward** [comment]
@seccubus refresh and see my last comment - i'm on a slow as sin connection right now.

**Comment by drwetter** [comment]
Oh, I see. Also on the linux binaries I compiled they are missing, ```testssl.sh -V 0xe ``` or ```./testssl.sh -V x0b``` doesn't show those.

@PeterMosmans: any clue why?

**Comment by seccubus** [comment]
Would you ba able to do a pcap though (later maybe). I will contact ssllabsa so the page can be fixed as well.

**Comment by teward** [comment]
@seccubus potentially, but lets wait.  Lets wait for @PeterMosmans to reply, because the binaries we use here and that @drwetter and I both use are from Peter's fork, so maybe it's his fork not including those ciphers?

**Comment by drwetter** [comment]
Well, the vanilla tree doesn't show it either.

From OpenSSL changelog:

 *) Removed support for the two export grade static DH ciphersuites
     EXP-DH-RSA-DES-CBC-SHA and EXP-DH-DSS-DES-CBC-SHA. These two ciphersuites
     were newly added (along with a number of other static DH ciphersuites) to
     1.0.2. However the two export ones have *never* worked since they were
     introduced. It seems strange in any case to be adding new export
     ciphersuites, and given "logjam" it also does not seem correct to fix them.
     [Matt Caswell]

**Comment by drwetter** [comment]
For the time being I commented the warning in.

It's unclear to me what is meant by "never worked". Maybe google helps here to find out. If they never did, we shouldn't bother for this PR at all.

**Comment by PeterMosmans** [comment]
Thanks @seccubus @drwetter @teward for the missing cipher note. I'll look into it (the 1.0.2-chacha fork) this weekend.

**Comment by PeterMosmans** [comment]
OK, I added (read: re-enabled) the ciphers. All internal openssl tests say _systems go_, but I haven't checked the ciphers out in the wild yet.

```
% openssl ciphers -l -V "ALL:COMPLEMENTOFALL"|grep -i "00,0x0[eb]"
          0x00,0x0E - EXP-DH-RSA-DES-CBC-SHA  SSLv3 Kx=DH/RSA   Au=DH   Enc=DES(40)   Mac=SHA1 export
          0x00,0x0B - EXP-DH-DSS-DES-CBC-SHA  SSLv3 Kx=DH/DSS   Au=DH   Enc=DES(40)   Mac=SHA1 export
```
183 ciphers. Yay!

See https://github.com/PeterMosmans/openssl for the latest version (fixed in https://github.com/PeterMosmans/openssl/commit/8ae2e1d49308e0b1ff2e91beca1ad04e6e163a9a )

Thanks once again for letting me know, enjoy!

Peter

**Comment by drwetter** [comment]
Am 16. Januar 2016 06:53:30 MEZ, schrieb Peter Mosmans <notifications@github.com>:
>OK, I added (read: re-enabled) the ciphers. All internal openssl tests
>say _systems go_, but I haven't checked the ciphers out in the wild
>yet.
>
>```
>% openssl ciphers -l -V "ALL:COMPLEMENTOFALL"|grep -i "00,0x0[eb]"
>0x00,0x0E - EXP-DH-RSA-DES-CBC-SHA  SSLv3 Kx=DH/RSA   Au=DH  
>Enc=DES(40)   Mac=SHA1 export
>0x00,0x0B - EXP-DH-DSS-DES-CBC-SHA  SSLv3 Kx=DH/DSS   Au=DH  
>Enc=DES(40)   Mac=SHA1 export
>```
>183 ciphers. Yay!
>
>See https://github.com/PeterMosmans/openssl for the latest version
>(fixed in
>https://github.com/PeterMosmans/openssl/commit/8ae2e1d49308e0b1ff2e91beca1ad04e6e163a9a
>)
>
>Thanks once again for letting me know, enjoy!

Well, thank *you*!

There's is one patch/contribution pending from me -- NNTPS support.

I'll make a new set of Linux/BSD binaries then and ping the others.

Cheers,Dirk 



-- 
Sent from my mobile

**Pull request merged**
