### PR TITLE
Shellcheck static analysis

### PR DESCRIPTION
**Pull request by feld**
I'm starting to push testssl.sh through shellcheck.sh's static analysis. The 2>&1 commit was actually wrong -- I had forgotten about the order issue.

The backticks to $(..) is really a style/modernization nitpick, but there are some other things that will be coming such as unquoted variables, misuse of variables in printf, etc. Ideally we'll have testssl.sh throwing no warnings when run through shellcheck and there will fewer issues to troubleshoot in the future. :-)

### CODE REVIEW

**Comment by feld** [comment]
Closing pull request until I work a few things out -- might just be FreeBSD / Linux differences -- we'll see.

**Comment by feld** [comment]
This is now stable/reliable/working on FreeBSD and Linux from what I can tell.

**Comment by drwetter** [comment]
Hi Mark,

static analysis sounds excellent! Also you get the trophy mentioning that you tested ;-)

But please ideally only one pull request per issue. I am probably not fine with the replacement of backticks, others I need to test, others are no-brainer to me.

Cheers, Dirk

**Comment by drwetter** [comment]
Thx Mark!

For some reaon I inititially thought that backticks don't fork a subshell and are faster. But that's wrong. expr should be changed in the future by bash internal arithmetic functions like $(()) or let.

Cheers, Dirk

**Comment by feld** [comment]
Sorry about the pull request mess. I have not yet taken the time to figure out why github wants to take every single commit and add it to an existing pull request. I suppose the solution is to create endless branches? *sigh*

**Comment by drwetter** [comment]
never mind. That's fine for now. Happy about the quality of what you did.

**Comment by drwetter** [comment]
Thx for the hint wrt shellcheck. Cool program! I did some minor improvements too but it's time consuming to weed out the stuff which doesn't make so much sense (mostly non-quoted variables which can't have a blank)

**Pull request merged**
