### PR TITLE
DNS CAA: drill query support.

### PR DESCRIPTION
**Pull request by k0ste**
#588

### CODE REVIEW

**Comment by k0ste** [comment]
[k0ste@WorkStation testssl.sh]$ EXPERIMENTAL=true ./testssl.sh -S posteo.de

```shell
###########################################################
    testssl.sh       2.9dev from https://testssl.sh/dev/
    (67fb3fe 2017-02-14 09:28:15 -- )

      This program is free software. Distribution and
             modification under GPLv2 permitted.
      USAGE w/o ANY WARRANTY. USE IT AT YOUR OWN RISK!

       Please file bugs @ https://testssl.sh/bugs/

###########################################################

 Using "OpenSSL 1.0.2-chacha (1.0.2i-dev)" [~183 ciphers]
 on WorkStation:$PWD/bin/openssl.Linux.x86_64
 (built: "Jun 22 19:32:29 2016", platform: "linux-x86_64")


 Start 2017-02-14 22:00:47    -->> 89.146.220.134:443 (posteo.de) <<--

 rDNS (89.146.220.134):  mail.posteo.de.
 Service detected:       HTTP


 Testing server defaults (Server Hello) 

 TLS extensions (standard)    "server name/#0" "renegotiation info/#65281" "EC point formats/#11" "session ticket/#35" "status request/#5" 
                              "heartbeat/#15" 
 Session Tickets RFC 5077     300 seconds (PFS requires session ticket keys to be rotated <= daily)
 SSL Session ID support       yes
 TLS clock skew               random values, no fingerprinting possible 
 Signature Algorithm          SHA256 with RSA
 Server key size              RSA 3072 bits
 Fingerprint / Serial         SHA1 BD167184B0B140D90A65998CE67B01D6AA5B8B67 / 3F5661607F9DDFD7659F12327AFFD28E
                              SHA256 302A06B8CFA85B93665A4466E2BB8405FE80953F5AFED108DB3BB00D7C42B439
 Common Name (CN)             posteo.de
 subjectAltName (SAN)         www.posteo.de m.posteo.de mx01.posteo.de mx02.posteo.de mx03.posteo.de mx04.posteo.de lists.posteo.de api.posteo.de 
                              cdn.posteo.de autodiscover.posteo.de payment.posteo.de status.posteo.de posteo.de 
 Issuer                       GeoTrust EV SSL CA - G4 (GeoTrust Inc. from US)
 Trust (hostname)             Ok via SAN and CN (works w/o SNI)
 Chain of trust               Ok   
 EV cert (experimental)       yes 
 Certificate Expiration       341 >= 60 days (2016-12-30 07:00 --> 2018-01-22 06:59 +0700)
 # of certificates provided   2
 Certificate Revocation List  http://gm.symcb.com/gm.crl
 OCSP URI                     http://gm.symcd.com
 OCSP stapling                offered
 DNS CAA RR (experimental)    OK (
issue
issuewild
iodef
issuewild
issue
issue
issuewild: 
startssl.com
d-trust.net
mailto:hostmaster@posteo.de
geotrust.com
geotrust.com
d-trust.net
startssl.com)
```

**Comment by drwetter** [comment]
Hi @k0ste ,

thx for the quick fix. Two remarks:

At the moment ``raw_caa`` is first a multi-line variable like
 ```
raw_caa='0 iodef "mailto:hostmaster@posteo.de"
0 issue "startssl.com"
0 issue "d-trust.net"
0 issuewild "startssl.com"
0 issuewild "d-trust.net"
0 issue "geotrust.com"
0 issuewild "geotrust.com"'
```
Later the output becomes a single line as it is a current feature which is missing here. In order to handle later this I would love to keep the raw_caa for drill similar to above.

Isn't  ``drill posteo.de type257  | awk "/^$1.*CAA/ "`` easier?

**Comment by k0ste** [comment]
Yes, but it's look like this.

```shell
[k0ste@WorkStation ~]$ drill posteo.de type257 | awk "/^$1.*CAA/ "
;; posteo.de.	IN	CAA
posteo.de.	16	IN	CAA	0 issue "geotrust.com"
posteo.de.	16	IN	CAA	0 iodef "mailto:hostmaster@posteo.de"
posteo.de.	16	IN	CAA	0 issuewild "d-trust.net"
posteo.de.	16	IN	CAA	0 issue "d-trust.net"
posteo.de.	16	IN	CAA	0 issuewild "startssl.com"
posteo.de.	16	IN	CAA	0 issue "startssl.com"
posteo.de.	16	IN	CAA	0 issuewild "geotrust.com"
```

With some adjustments:

```shell
[k0ste@WorkStation ~]$ drill posteo.de type257 | awk "/^$1.*CAA/" | sed 1d | awk '{ print $5,$6,$7 }'
0 issuewild "startssl.com"
0 issuewild "d-trust.net"
0 issue "d-trust.net"
0 issue "geotrust.com"
0 iodef "mailto:hostmaster@posteo.de"
0 issue "startssl.com"
0 issuewild "geotrust.com"
```

This better?

**Comment by drwetter** [comment]
in principle yes, but  we can save 1x sed and do awk in one shot :

```
dirks@laptop:~|0% a=posteo.de                                                                 
dirks@laptop:~|0% drill $a type257 | awk '/'"^${a}"'.*CAA/ { print  $5,$6,$7 }'
0 issuewild "d-trust.net"
0 iodef "mailto:hostmaster@posteo.de"
0 issuewild "startssl.com"
0 issue "startssl.com"
0 issue "d-trust.net"
0 issue "geotrust.com"
0 issuewild "geotrust.com"
dirks@laptop:~|0% 
```

**Comment by k0ste** [comment]
Yes, I'm not good in shell... Commit rebased, check it now.

**Comment by drwetter** [comment]
Thank you!

It's just that readability and doing things as easy as possible becomes more important as the project gets bigger and bigger

**Pull request merged**
