### PR TITLE
add drill support

### PR DESCRIPTION
**Pull request by k0ste**
Add drill (ldns lib) support.

...and github atom editor delete not needed spaces - if is problem, I can send clean patch. Thanks.

### CODE REVIEW

**Comment by drwetter** [comment]
Hi @k0ste,

thx for the hint and your PR. Didn't know drill yet, the company developed that rings a bell though.

One problem is the availability: I searched on several platforms (Debian, Opensuse, CentOS, Ubuntu LTS) for drill, assuming the name of the binary is also the name of the package. I wasn't able to find it.

Cheers, Dirk

**Comment by k0ste** [comment]
Try search package 'ldns'.

**Comment by drwetter** [comment]
Out of the systems above only Opensuse has the package. I am also not convinced about the necessity.

Sorry & thx

**Comment by k0ste** [comment]
Ubuntu 14.04:
```
Linux usachaa-KVM 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux 
root@usachaa-KVM:~# apt-cache search ldns 
libldns-dev - ldns library for DNS programming 
libldns1 - ldns library for DNS programming 
ldnsutils - ldns library for DNS programming 
libnet-dns-fingerprint-perl - library to determine DNS server vendor, product and version 
python-ldns - Python bindings for the ldns library for DNS programming 
rbldnsd - small nameserver daemon designed for DNSBLs 
libldns1-dbg - ldns library for DNS programming (debug symbols)
```

Debian 8
```
Linux napaster 2.6.32-042stab111.11 #1 SMP Tue Sep 1 18:19:12 MSK 2015 x86_64 GNU/Linux 
root@napaster:~# aptitude search ldns 
p   ldnsutils                                                                                                       - ldns library for DNS programming                                                                                          
p   libldns-dev                                                                                                     - ldns library for DNS programming                                                                                          
p   libldns1                                                                                                        - ldns library for DNS programming                                                                                          
p   libldns1-dbg                                                                                                    - ldns library for DNS programming (debug symbols)                                                                          
p   python-ldns                                                                                                     - Python bindings for the ldns library for DNS programming                                                                  
v   python2.7-ldns                                                                                                  -                                                                                                                           
p   rbldnsd                                                                                                         - small nameserver daemon designed for DNSBLs                                                                               
```

Centos 7.1:

```
Linux mon 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[k0ste@mon ~]$ yum search ldns
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.logol.ru
 * epel: mirror.logol.ru
 * extras: mirror.logol.ru
 * updates: mirror.logol.ru
================================================================= N/S matched: ldns ==================================================================
ldns-devel.i686 : Development package that includes the ldns header files
ldns-devel.x86_64 : Development package that includes the ldns header files
ldns-doc.noarch : Documentation for the ldns library
ldns-python.x86_64 : Python extensions for ldns
ldns.i686 : Low-level DNS(SEC) library with API
ldns.x86_64 : Low-level DNS(SEC) library with API
rbldnsd.x86_64 : Small, fast daemon to serve DNSBLs
```

OpenWRT:

```
Linux OpenWrt 4.1.5 #1 Tue Aug 18 19:14:02 NOVT 2015 mips GNU/Linux
root@OpenWrt:~# opkg list|grep ldns
libldns - 1.6.17-1
```

ArchLinux:

```
Linux WorkStation 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
[k0ste@WorkStation ~]$ pacman -Ss ldns
core/ldns 1.6.17-3 [installed]
```

**Comment by drwetter** [comment]
Sorry my fault then. Don't know what happened yesterday.

Still, the question remains about why it is needed as I assume most folks will have either nslookup, dig or host installed. This seems to be the case for most systems. Only CentOS 7 doesn't seem to have none of them on one of my installations, but also no ldns.

**Comment by k0ste** [comment]
I use ArchLinux on my laptop. ldns on core repository (installed by default) => drill in complect.
As recursive nameserver I use unbound. Unbound work on ldns lib => drill on comlect.

Installing bind-tools packages is rudiment, if all work on one lib. I think.

**Comment by drwetter** [comment]
Hi @k0ste,

Ok, thx. Could you please rebase the patch? (with or without line end cleanings).

Cheers, Dirk

**Comment by PeterMosmans** [comment]
@k0ste , what are the advantages of using drill over the current solutions ?

msys2 on Win64 has support: 
```
 % Pacman -Ss ldns
mingw32/mingw-w64-i686-ldns 1.6.17-4
    Fast DNS library supporting recent RFCs (mingw-w64)
mingw64/mingw-w64-x86_64-ldns 1.6.17-4
    Fast DNS library supporting recent RFCs (mingw-w64)

```

**Comment by k0ste** [comment]
@PeterMosmans, drill support recent RFC and designed to work with DNSSEC. For me - not necessary install package bind-tools, and on OpenWRT (8mb flash) ability to install resolver tool if used unbound, instead dnsmasq.

**Comment by k0ste** [comment]
@drwetter, created here... #240

**Pull request closed without merging**
