### PR TITLE
added --colorblind and --mapping options

### PR DESCRIPTION
**Pull request by thecky**

### CODE REVIEW

**Comment by drwetter** [comment]
Thanks Thomas! Also bear with me pls.

**Comment by drwetter** [comment]
Thx a bunch, Thomas! Pls also bear w/ me.

**Comment by thecky** [comment]
Hi Dirk, I renamed the (most) pr_* functions and tput variables (f.e. pr_red -> pr_svrty_critical) as first step related to #232.
In set_color_functions() is now the "color-blind option" (swap green/blue #236) implemented, for tput and bash colorcodes.
The --mapping=no-rfc option suppress the cipher RFC-names in the output and also the width adjustment for "KeyExch." is fixed for COLOR=1.

**Comment by drwetter** [comment]
Hi Thomas,

thx first! And sorry I didn't notice the commit 5 days ago -- strange.

Another bigger merge.. hmm.. Same as for the other pull requests: In the future pls only one thing at a time, it makes a review and testing easier (here e.g.: 1: the color blind + rename thing 2: the rfc thingy).

Hope I find the time before Xmas to merge this manually (branch conflicts). Pls bear with me.

Cheers, Dirk

**Comment by drwetter** [comment]
As ``--mapping=rfc`` is the default, is there any reason we need it?

**Comment by thecky** [comment]
Well, due the fact that --mapping=rfc is the default, I can remove the "rfc" - is just one line. If there's no other need for a later additional parameter (like no-ossl), I can also change this to an boolean option (f.e. --no-rfc-mapping).

To the ANSI escape codes - I think you mean the ANSI block between the two tput blocks (~line 423 and 473). These ANSI blocks can also be moved to the end of the if/else block (so the order is tput, tput (old bsd), ansi - instead tput, ansi, tput (old bsd)). Or do you mean an separate set_color_function for the ANSI codes?

**Comment by drwetter** [comment]
Hi Thomas,

Later on I would love t have just the RFC/IANA style cipher name instead of the ones from OpenSSL  -- per switch -- but I would be happy for now if there would be just this one option to remove the RFC ones. If not wanted otherwise people need to remove the file -- kind of ugly as next occasion it'll show up again.

ANSI is @ https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L293-L346 . Termcap/terminfo @ https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L293-L346 . Those are two different things. Maybe testssl would only need one but I do not see a reason to mix the two parts today. Reversing https://github.com/thecky/testssl.sh/commit/d5e7d14ea9e75f9337514a36afe6e53dbec40026 should do it.

Cheers, Dirk

**Pull request closed without merging**
