### PR TITLE
Avoidance of escape characters in JSON and CSV reports

### PR DESCRIPTION
**Pull request by AlGreed**
Hi,

To avoid escape characters in json and csv reports i would suggest to set COLOR to zero by default for these formats.

 **JSON with escape charachters:**
```
  "id"           : "cipher_xc030",
  "severity"     : "INFO",
  "finding"      : "xc030   ECDHE-RSA-AES256-GCM-SHA384       ECDH [0;32m571 [m  AESGCM    256      TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
 },{
  "id"           : "cipher_xc028",
  "severity"     : "INFO",
  "finding"      : "xc028   ECDHE-RSA-AES256-SHA384           ECDH [0;32m571 [m  AES       256      TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
},{
```

 **CSV with escape charachters:**
```
"cipher_xc030","xxx","INFO","xc030 ECDHE-RSA-AES256-GCM-SHA384 ECDH [0;32m570 [m AESGCM 256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","","",""
"cipher_xc028","xxx","INFO","xc028 ECDHE-RSA-AES256-SHA384 ECDH [0;32m570 [m AES 256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384","","",""
```

**Other options:**
1. filter escape characters in fileout function: i would say it would be a clean solution, but not so high-performance. 
2. any another one?

### CODE REVIEW

**Comment by dcooper16** [comment]
I'm not getting any escape characters when I create JSON or CSV reports. `fileout()` calls `strip_quote()`, which filters out the escape characters. Below is what I see when I run the current 2.9dev branch of testssl.sh with "bash -x -v". Could you try running the script using the "-x -v" options and show the part where fileout is called with a "finding" that includes color information. Perhaps the current code is working correctly on some platforms, but not others.

```
2499> run_allciphers(): fileout cipher_xc011 INFO ' xc011   ECDHE-RSA-RC4-SHA                 ECDH ^[[0;32m256 ^[[m  RC4       128      TLS_ECDHE_RSA_WITH_RC4_128_SHA                      '
865> fileout(): local severity=INFO
866> fileout(): local cwe=
867> fileout(): local hint=
869> fileout(): show_finding INFO
301> show_finding(): local severity=INFO
303> show_finding(): [[ INFO == \D\E\B\U\G ]]
304> show_finding(): [[ INFO == \W\A\R\N ]]
305> show_finding(): [[ INFO == \I\N\F\O ]]
305> show_finding(): [[ 0 -le 0 ]]
strip_lf "$(newline_to_spaces "$(strip_quote "$3")")"
newline_to_spaces "$(strip_quote "$3")"
strip_quote "$3"
888870> fileout(): strip_quote ' xc011   ECDHE-RSA-RC4-SHA                 ECDH ^[[0;32m256 ^[[m  RC4       128      TLS_ECDHE_RSA_WITH_RC4_128_SHA                      '
666698> strip_quote(): sed -e 's,\x1B\[[0-9;]*[a-zA-Z],,g' -e 's/"/\'\''/g' -e 's/^ *//g' -e 's/ *$//g'
88870> fileout(): newline_to_spaces 'xc011   ECDHE-RSA-RC4-SHA                 ECDH 256   RC4       128      TLS_ECDHE_RSA_WITH_RC4_128_SHA'
99917> newline_to_spaces(): tr '\n' ' '
99917> newline_to_spaces(): sed 's/ $//'
8870> fileout(): strip_lf 'xc011   ECDHE-RSA-RC4-SHA                 ECDH 256   RC4       128      TLS_ECDHE_RSA_WITH_RC4_128_SHA'
9925> strip_lf(): tr -d '\n'
9925> strip_lf(): tr -d '\r'
870> fileout(): local 'finding=xc011   ECDHE-RSA-RC4-SHA                 ECDH 256   RC4       128      TLS_ECDHE_RSA_WITH_RC4_128_SHA'
872> fileout(): is_json_format
832> is_json_format(): [[ -f '' ]]
875> fileout(): true
876> fileout(): echo -e '"cipher_xc011","127.0.0.1/127.0.0.1","443","INFO","xc011' ECDHE-RSA-RC4-SHA ECDH 256 RC4 128 'TLS_ECDHE_RSA_WITH_RC4_128_SHA","","",""'
878> fileout(): false
```

**Comment by drwetter** [comment]
same here. Just was diff'ing the file outputs with and without ``color=0``

**Comment by AlGreed** [comment]
Nope. not working. 

>  bash-3.2$ bash -x -v ./testssl.sh --json-pretty -e server:port >> output.txt

I cant show it with my output. But "1024" in the next snippet is yellow **everywhere**, even in 597>

```
strip_quote "$3"
666642> fileout(): strip_quote ' x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256                 '
444498> strip_quote(): sed -e 's,\x1B\[[0-9;]*[a-zA-Z],,g' -e 's/"/\'\''/g' -e 's/^ *//g' -e 's/ *$//g'
66642> fileout(): newline_to_spaces 'x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256'
66688> newline_to_spaces(): tr '\n' ' '
66688> newline_to_spaces(): sed 's/ $//'
6642> fileout(): strip_lf 'x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256'
6696> strip_lf(): tr -d '\n'
6696> strip_lf(): tr -d '\r'
642> fileout(): local 'finding=x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256'
644> fileout(): is_json_format
606> is_json_format(): [[ -f ggg-20161214-1753.json ]]
606> is_json_format(): false
606> is_json_format(): true
644> fileout(): fileout_json_finding cipher_x9e INFO 'x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256'
585> fileout_json_finding(): false
595> fileout_json_finding(): true
596> fileout_json_finding(): false
596> fileout_json_finding(): echo -n ',{'
597> fileout_json_finding(): echo -e -n '
                                "id"           : "cipher_x9e",
                                "severity"     : "INFO",
                                "finding"      : "x9e     DHE-RSA-AES128-GCM-SHA256         DH 1024    AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
                           }'
```
JSON:
```
                           },{
                                "id"           : "cipher_x9e",
                                "severity"     : "INFO",
                                "finding"      : "x9e     DHE-RSA-AES128-GCM-SHA256         DH [0;33m1024 [m   AESGCM    128      TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
                           },{
```

**Comment by AlGreed** [comment]
Nope. not working.

> bash-3.2$ bash -x -v ./testssl.sh --json-pretty -e server:port >> output.txt

I cant show it with my output. But "1024" in the next snippet is yellow everywhere, even in 872>

```
22187> neat_list(): printf -- ' %-7s %-33s %-10s %-10s%-8s %-49s  %-0s' x6b DHE-RSA-AES256-SHA256 'DH 1024   ' AES 256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
2499> run_allciphers(): fileout cipher_x6b INFO ' x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256                 '
865> fileout(): local severity=INFO
866> fileout(): local cwe=
867> fileout(): local hint=
869> fileout(): show_finding INFO
301> show_finding(): local severity=INFO
303> show_finding(): [[ INFO == \D\E\B\U\G ]]
304> show_finding(): [[ INFO == \W\A\R\N ]]
305> show_finding(): [[ INFO == \I\N\F\O ]]
305> show_finding(): [[ 0 -le 0 ]]
strip_lf "$(newline_to_spaces "$(strip_quote "$3")")"
newline_to_spaces "$(strip_quote "$3")"
strip_quote "$3"
888870> fileout(): strip_quote ' x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256                 '
666698> strip_quote(): sed -e 's,\x1B\[[0-9;]*[a-zA-Z],,g' -e 's/"/\'\''/g' -e 's/^ *//g' -e 's/ *$//g'
88870> fileout(): newline_to_spaces 'x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256'
99917> newline_to_spaces(): tr '\n' ' '
99917> newline_to_spaces(): sed 's/ $//'
8870> fileout(): strip_lf 'x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256'
9925> strip_lf(): tr -d '\n'
9925> strip_lf(): tr -d '\r'
870> fileout(): local 'finding=x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256'
872> fileout(): is_json_format
832> is_json_format(): [[ -f host_port-20161214-1817.json ]]
832> is_json_format(): false
832> is_json_format(): true
872> fileout(): fileout_json_finding cipher_x6b INFO 'x6b     DHE-RSA-AES256-SHA256             DH 1024    AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256' '' '' ''
805> fileout_json_finding(): false
818> fileout_json_finding(): true
819> fileout_json_finding(): false
```

```
JSON:


},{
         "id"           : "cipher_x6b",
         "severity"     : "INFO",
         "finding"      : "x6b     DHE-RSA-AES256-SHA256             DH [0;33m1024 [m   AES       256      TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"
},{
```

**Comment by drwetter** [comment]
please do a fresh pull of 2.9dev and run it against dev.testssl.sh .

I can't still reproduce it.

**Comment by AlGreed** [comment]
i have just downloaded direkt from github the latest 2.9dev version. You can see the functions order is the same.

It seems -v for bash does not work. hmm. Did i call script right?

**Comment by AlGreed** [comment]
Just checked it on selinux - **No Problem**. So it is really the fault of my MAC.

**Comment by AlGreed** [comment]
We have in code:
`743>  sed -e "s,\x1B\[[0-9;]*[a-zA-Z],,g" \`

It does not work for "my" Mac. Nice.

Ok. Just tried about 10 different variants.

If i put $ and use ' ' instead of "", then it works well. hmm.
`sed $'s,\x1b\[[0-9;]*[a-zA-Z],,g'
`

Another variant that works for me is:
`sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g"
 `

**Comment by drwetter** [comment]
can reproduce it on FreeBSD 9.x -- only the yellow part

**Comment by drwetter** [comment]
swapping the cuplit with ``sed -e "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g" \`` works under FreeBSD and Linux.

Mind changing the PR, @AlGreed ?

**Comment by AlGreed** [comment]
will you commit it? If yes - i ll close the this PR, otherwise i ll change and commit it.

**Comment by dcooper16** [comment]
Thanks @AlGreed ,

I just tried it on a Mac and got the same results as you did, and I believe I found the source of the problem. According to http://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed:

> GNU sed interprets escape sequences like `\t`, `\n`, `\001`, `\x01`, `\w`, and `\b`. OS X's sed and POSIX sed only interpret \n (but not in the replacement part of `s`).

I looked at http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed, and a commenter there also noted  that "OS X sed doesn't recognize the \xnn escapes." The commenter who noted that seems to suggest using different "sed" lines for OS X and Linux, but an alternative that I got from that web site and that seems to be working is to replace `\x1B` with `$(echo -e "\033")` to get:
```
strip_quote() {
     # remove color codes (see http://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed)
     #  \', leading and all trailing spaces
     sed -e "s,$(echo -e "\033")\[[0-9;]*[a-zA-Z],,g" \
          -e "s/\"/\\'/g" \
          -e 's/^ *//g' \
          -e 's/ *$//g' <<< "$1"
}
```

**Comment by AlGreed** [comment]
Adapted:
* removed setting the COLOR to zero
* applied strip_quote

**Comment by drwetter** [comment]
Thanks!

**Pull request merged**
