### PR TITLE
Refactor strip_quote to use bash replacements instead of sed

### PR DESCRIPTION
**Pull request by h3xx**

### CODE REVIEW

**Comment by drwetter** [comment]
Hi,

thanks! Certainly better than sed. What would be needed is a comment in the code why curly braces are not wanted here. For most it's not clear probably.

Only the spelllcheck action runs automatically. So I rather pass this to @dcooper16 for review.

**Comment by h3xx** [comment]
The `()` are to prevent variables from polluting/clobbering the global script variables. I suppose I could use a `local` instead, but then I wouldn't be showing you you could use this syntax. ;-)

In refactoring the function, I set up an a/b testing script, included below:

```sh

**Comment by h3xx** [comment]
The `()` are to prevent variables from polluting/clobbering the global script variables, as well as to prevent `extglob` from affecting the rest of the script. I suppose I could use a `local` instead, but then I wouldn't be showing you you could use this syntax. ;-)

In refactoring the function, I set up an a/b testing script, included below:

```sh
#!/bin/bash
# vi: et sts=5 sw=5 ts=5
SETCOLOR_FAILURE=$'\e[1;31m'
SETCOLOR_SUCCESS=$'\e[1;32m'
RESET=$'\e[0m'

strip_quote_old() {
     # remove color codes (see https://www.commandlinefu.com/commands/view/3584/remove-color-codes-special-characters-with-sed)
     #  \', leading and all trailing spaces
     sed -e "s,$(echo -e "\033")\[[0-9;]*[a-zA-Z],,g" \
          -e "s/\"/\\'/g" \
          -e 's/^ *//g' \
          -e 's/ *$//g' <<< "$1"
}

# https://web.archive.org/web/20121022051228/http://codesnippets.joyent.com/posts/show/1816
strip_leading_space() {
     printf "%s" "${1#"${1%%[![:space:]]*}"}"
}
strip_trailing_space() {
     printf "%s" "${1%"${1##*[![:space:]]}"}"
}

strip_quote() (
     shopt -s extglob
     # Remove color codes
     OUT=${1//$'\e['*([0-9;])[a-zA-Z]}
     # Replace quotes
     OUT=${OUT//\"/\'}
     strip_leading_space "$(
          strip_trailing_space "$OUT"
     )"
)

TESTS=(
     'Foo"Bar'
     'Foo\"Bar'
     'Foo'\''Bar'
     ' Foo'\''Bar'
     '     '
     ''
     ' Foo     Bar'
     '      Foo     Bar'
     'Foo     Bar'
     'Foo     Bar '
     'Foo     Bar     '
     $'\e[1;33mFoo Bar\e[0m'
     $'\e[1;33mFoo Bar \e[0m'
     $'\e[1;33m    Foo     Bar   \e[0m  '
)

MAXLEN_TEST=0
MAXLEN_SHOULD=0
MAXLEN_IS=0
PAD=4
RESULTS=()
for TEST in "${TESTS[@]}"; do
     SHOULD=$(strip_quote_old "$TEST")
     IS=$(strip_quote "$TEST")

     RESULTS+=(
          "$TEST"
          "$SHOULD"
          "$IS"
     )

     if [[ ${#SHOULD} -gt $MAXLEN_SHOULD ]]; then
          MAXLEN_SHOULD=${#SHOULD}
     fi
     if [[ ${#TEST} -gt $MAXLEN_TEST ]]; then
          MAXLEN_TEST=${#TEST}
     fi
     if [[ ${#IS} -gt $MAXLEN_IS ]]; then
          MAXLEN_IS=${#IS}
     fi
done

let MAXLEN_IS+=2 MAXLEN_TEST+=2 MAXLEN_SHOULD+=2

for (( I=0; I < ${#RESULTS[@]}; )); do
     TEST=${RESULTS[I]}
     let ++I
     SHOULD=${RESULTS[I]}
     let ++I
     IS=${RESULTS[I]}
     let ++I

     if [[ $IS = "$SHOULD" ]]; then
          COLOR=$SETCOLOR_SUCCESS
     else
          COLOR=$SETCOLOR_FAILURE
     fi

     printf "%-${MAXLEN_TEST}s: %-${MAXLEN_SHOULD}s | %s%-${MAXLEN_IS}s%s"'\n' \
          "'$TEST'" \
          "'$SHOULD'" \
          "$COLOR" \
          "'$IS'" \
          "$RESET"
done
```

**Comment by drwetter** [comment]
> as well as to prevent extglob from affecting the rest of the script.

exactly, that would be important to insert as a comment in the code, please.

**Comment by h3xx** [comment]
Done.

**Comment by drwetter** [comment]
Thank you!

**Pull request merged**
