### PR TITLE
Update Safari to 13.0 and macOS to 10.14

### PR DESCRIPTION
**Pull request by csett86**
manually wiresharked, now with TLS1.3 for macOS as well.

### CODE REVIEW

**Comment by drwetter** [comment]
Thank you!

**Comment by drwetter** [comment]
How about iOS? ;-)

**Comment by csett86** [comment]
Nothing has changed in Safari on iOS, TLS 1.3 was already working with the iOS version in it. But maybe I‘ll doublecheck ATS...

**Comment by drwetter** [comment]
Even if it hasn't changed: Feel free to submit that with another label.

I am not really up to date with versions in the Mac world. For Android I looked at the usage and included a reasonable old version and newer versions which are still in use.

If you or anybody else feel we should drop e.g. "Safari 10 OS X 10.12" to be listed by default because nobody's using it pls. let me know.

**Pull request merged**
