### PR TITLE
Getopts

### PR DESCRIPTION
**Pull request by PeterMosmans**
This is a major change with lots of refactoring and small changes. I tried to keep this change as atomic as possible, but the main code part touches a lot of different functions, hence the big chunk.

@drwetter , please test this change thoroughly with your magic testscripts on as much platforms as possible before pushing everything to the main branch. I haven't tested all possible operating system/flags, so there could be still some bugs lingering around (in theory at least ;)

Note that due to the refactoring of some status messages, the output will be slightly different (more verbose) than previous versions. This can be changed of course

Moved specific status messages to http_header()
Moved specific status messages to breach()
Moved specific status messages to ccs_injection()
Moved specific status messages to heartbleed()
Moved specific status messages to renego()
Moved specific status messages to crime()
Moved specific status messages to tls_poodle()
Moved specific status messages to freak()
Moved specific status messages to beast()

Added some more documentation for functions

Fixed typos in help

Created new function main:
This is the main function of testssl.sh
Refactored major part of the original main function

Created new function startup:
Parses the startup options

Created new function intialize_globals:
Initializes all used global variables

Created new function scanning_defaults:
Sets default scanning options, when only one parameter (URI) is given

TODO: Refactor more/duplicate parts of functions

Note: For the new functions, fixed spaces (4) are used instead of tabs

### CODE REVIEW

**Comment by drwetter** [comment]
Hi Peter,

thx! I like your style. :)  Now only I need to run and test it. 

If I understand correctly only the last patch is the one to the actual master branch, right?

Cheers, Dirk

**Comment by PeterMosmans** [comment]
Good to hear :)
Yeah, accidentally I didn't use the upstream/master (upstream = yours, drwetter) as base, but this shouldn't be a problem when applying the patch.
If this poses a problem I can create a new pull request based on the proper upstream master.

Good luck testing...

**Comment by drwetter** [comment]
Am 22. März 2015 11:02:59 MEZ, schrieb Peter Mosmans <notifications@github.com>:
>Good to hear :)

Sure. 

>Yeah, accidentally I didn't use the upstream/master (upstream = yours,
>drwetter) as base, but this shouldn't be a problem when applying the
>patch.
>If this poses a problem I can create a new pull request based on the
>proper upstream master.

I am not that good with github yet ;) I'll try, hints appreciated. If it doesn't cause much work a new pull request would ease matters.

Just let me know what you think and we go from there. 

Cheers, Dirk

**Comment by PeterMosmans** [comment]
Closing this pull request, please see new one (#79)

**Pull request closed without merging**
