### PR TITLE
Support of multiple servers for JSON-PRETTY

### PR DESCRIPTION
**Pull request by AlGreed**
Changed structure:
* scanResult is an array up now
* removed service section
* put service finding to a new field
* moved ip field

```
          "port"        : "25",
          "startTime"   : "1485586338",
          "scanResult"  : [
          {
                    "service"         : "Service detected: smtp",
                    "ip"              : "xxx",
                    "protocols"         : [
                            {
                                "id"           : "sslv2",
                                "severity"     : "OK",
                                "finding"      : "SSLv2 is not offered"


```

* added fileout to STARTTLS:
```
                     out " Service set:$CORRECT_SPACES            STARTTLS via "
+                   fileout "service" "INFO" "$protocol"
```

### CODE REVIEW

**Comment by drwetter** [comment]
Thank you!

One minor thing/request: ``target host`` is still empty using ``--mx``. Can't this be the supplied hostname?

**Comment by drwetter** [comment]
And adding below the IP the current hostname would be awesome. It would be better aligned with the screen output. For non-``--mx`` it is already in ``targethost``,  so great would be:

```
         "openssl"     : "1.0.2-chacha from Jun 22 19:32:29 2016",
         "target host" : "mailbox.org",
          "port"        : "25",
          "startTime"   : "1485595577",
          "scanResult"  : [
          {
                    "service"         : "smtp",
                    "ip"              : "80.241.60.212",
                    "host"            :  "mx1.mailbox.org" 
                    "protocols"         : [
                            {
                                "id"           : "sslv2",
                                "severity"     : "OK",
                                "finding"      : "SSLv2 is not offered"
                           },{
                                "id"           : "sslv3",
[..]
```

**Comment by AlGreed** [comment]
@drwetter  Should i revert this PR to add those things?

Added hostname and target host is either URI or NODE:
```
+    target="$NODE"
+    $do_mx_all_ips && target="$URI"
```

```

          "target host" : "mailbox.org",
          "port"        : "25",
          "startTime"   : "1485623190",
          "scanResult"  : [
          {
                    "service"         : "smtp",
                    "ip"              : "80.241.60.212",
                    "hostname"        : "mx1.mailbox.org",
                    "protocols"         : [
                            {
```

**Comment by drwetter** [comment]
Not revert. That was good work. If you happen to have the chance just to add this would be great.

Sorry about the confusion  Maybe open an issue would have been better 

⁣-- 
Sent via mobile. Excuse my brevity, my typos and the autocorrection​

**Pull request merged**
