### PR TITLE
Test for vulnerability to Bleichenbacher attack

### PR DESCRIPTION
**Pull request by dcooper16**
This PR adds a test to check whether a server that supports ciphers suites that use RSA key transport (TLS_RSA) are vulnerable to Bleichenbacher attacks (see http://archiv.infsec.ethz.ch/education/fs08/secsem/bleichenbacher98.pdf).

### CODE REVIEW

**Comment by drwetter** [comment]
Thx

**Comment by dcooper16** [comment]
As noted in the comment at the top of the function, `run_robot()` was developed based on "Return Of Bleichenbacher’s Oracle Threat (ROBOT)" by Hanno Böck, Juraj Somorovsky, and Craig Young (see https://robotattack.org). The code in  `run_robot()` is basically just a Bash implementation of the test code that they developed (see https://github.com/robotattackorg/robot-detect).

**Comment by drwetter** [comment]
> The code in run_robot() is basically just a Bash implementation ...

is just is a little bit of an understatement ;-)

**Comment by franklinyu** [comment]
ROBOT attack is not released right? I can only find it in `2.9dev` branch.

**Comment by drwetter** [comment]
Depends how you read it. Of course it is released (in 2.9dev) but in the stable version (2.9.5) you won't get new features. The ROBOT check is a new feature.

Either you do a git pull from ``2.9dev`` or get the zip file from https://testssl.sh/bleichenbacher/testssl-robot.zip.

**Pull request merged**
