### PR TITLE
Improve SSL native client simulation

### PR DESCRIPTION
**Pull request by dcooper16**
This PR improves client simulation in "--ssl-native" mode:

* It changes `${protos[i]}` to list the protocols that should be disabled rather than those that should be enabled, except in the case that the client only supports one protocol.

* It sets the values for `${tlsvers[i]}`, which is used in `run_client_simulation()`, but was not defined.

* It adds a new variable, `${ciphersuites[i]}`, that lists the TLSv1.3 cipher suites supported by a client.

Client simulation still produces false results in "--ssl-native" mode, but the results are better than before.

### CODE REVIEW

**Comment by dcooper16** [comment]
I just added a second commit to improve the client simulation results even further. This commit extracts the list of supported elliptic curves for each client and passes that information to `$OPENSSL s_client`. There are still some false results, but much fewer.

Since `run_client_simulation()` and `run_pfs()` both need information about the set of curves that `$OPENSSL` supports for the `-curves` option of `s_client`, I moved the code to obtain that information out of `run_pfs()` and into `find_openssl_binary()`, with the information being stored in `$OSSL_SUPPORTED_CURVES`.

**Comment by drwetter** [comment]
With OpenSSL 1.1.1 (I used above the complementary binary in this repo) the comparison is not as good: every host tested shows a difference. Surprisingly the difference cannot be as easy explained as the ciphers basically are available in OpenSSL 1.1.1:


| Node | client |  sockets | openssl |
----------|--------|-------------|------------|
| Ubuntu 12.04 (internal) | clientsimulation-android_237 |  RC4-MD5   |  RC4-SHA  |
| Ubuntu 12.04 (internal) | clientsimulation-chrome_57_win7| AES128-GCM-SHA256   |   no  connection |
| Ubuntu 12.04 (internal) | clientsimulation-firefox_53_win7 |DHE-RSA-AES128-SHA    |   no  connection |
| Ubuntu 12.04 (internal) | clientsimulation-ie_6_xp  |  RC4-MD5   |  RC4-SHA  |
| Ubuntu 12.04 (internal) | clientsimulation-ie_8_xp  |  RC4-MD5   |  RC4-SHA  |
| Ubuntu 12.04 (internal) | clientsimulation-java_6u45 |  RC4-MD5   |  RC4-SHA  |
| Ubuntu 12.04 (internal) | clientsimulation-ie_8_xp  |DHE-RSA-AES128-SHA    |   no  connection |
| google.de | clientsimulation-android_70    | ECDHE-RSA-CHACHA20-POLY1305 | ECDHE-RSA-AES128-GCM-SHA256|                                         
| google.de | clientsimulation-chrome_57_win7|  ECDHE-ECDSA-AES128-GCM-SHA256 |   no  connection |
| google.de | clientsimulation-firefox_53_win7 |  ECDHE-ECDSA-AES128-GCM-SHA256 |   no  connection |
| testssl.net | clientsimulation-chrome_57_win7|  ECDHE-ECDSA-AES128-GCM-SHA256 |   no  connection |
| testssl.net | clientsimulation-firefox_53_win7 |  ECDHE-ECDSA-AES128-GCM-SHA256 |   no  connection |
| testssl.sh | clientsimulation-chrome_57_win7|  ECDHE-RSA-AES256-GCM-SHA384  |   no  connection |
| testssl.net | clientsimulation-firefox_53_win7 |  ECDHE-RSA-AES256-GCM-SHA384 |   no  connection |

**Comment by dcooper16** [comment]
I tried OpenSSL 1.1.1 with google.de and testssl.net and did not get the same results as you did. The only differences I saw were the following:

Node | client | sockets | openssl
-- | -- | -- | --
google.de | IE 8 XP | DES-CBC3-SHA  | no  connection
testssl.net | Android 5.0.0 | ECDHE-ECDSA-CHACHA20-POLY1305-OLD | ECDHE-ECDSA-AES128-GCM-SHA256
testssl.net | Android 6.0 | ECDHE-ECDSA-CHACHA20-POLY1305-OLD | ECDHE-ECDSA-AES128-GCM-SHA256

I can't fully explain the results you got on your internal server, but I know that OpenSSL 1.1.1 does not support RC4-MD5. When using `ciphers` to list only supported ciphers (`-s`), it does not appear in the list.

```
> openssl version
OpenSSL 1.1.1-pre5-dev  xx XXX xxxx
> openssl ciphers -ciphersuites '' -V RC4
          0xC0,0x07 - ECDHE-ECDSA-RC4-SHA     TLSv1 Kx=ECDH     Au=ECDSA Enc=RC4(128)  Mac=SHA1
          0xC0,0x11 - ECDHE-RSA-RC4-SHA       TLSv1 Kx=ECDH     Au=RSA  Enc=RC4(128)  Mac=SHA1
          0xC0,0x16 - AECDH-RC4-SHA           TLSv1 Kx=ECDH     Au=None Enc=RC4(128)  Mac=SHA1
          0x00,0x18 - ADH-RC4-MD5             SSLv3 Kx=DH       Au=None Enc=RC4(128)  Mac=MD5 
          0xC0,0x33 - ECDHE-PSK-RC4-SHA       TLSv1 Kx=ECDHEPSK Au=PSK  Enc=RC4(128)  Mac=SHA1
          0x00,0x92 - RSA-PSK-RC4-SHA         SSLv3 Kx=RSAPSK   Au=RSA  Enc=RC4(128)  Mac=SHA1
          0x00,0x8E - DHE-PSK-RC4-SHA         SSLv3 Kx=DHEPSK   Au=PSK  Enc=RC4(128)  Mac=SHA1
          0x00,0x05 - RC4-SHA                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=SHA1
          0x00,0x04 - RC4-MD5                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=MD5 
          0x00,0x8A - PSK-RC4-SHA             SSLv3 Kx=PSK      Au=PSK  Enc=RC4(128)  Mac=SHA1
> openssl ciphers -ciphersuites '' -s -V RC4
          0xC0,0x07 - ECDHE-ECDSA-RC4-SHA     TLSv1 Kx=ECDH     Au=ECDSA Enc=RC4(128)  Mac=SHA1
          0xC0,0x11 - ECDHE-RSA-RC4-SHA       TLSv1 Kx=ECDH     Au=RSA  Enc=RC4(128)  Mac=SHA1
          0x00,0x05 - RC4-SHA                 SSLv3 Kx=RSA      Au=RSA  Enc=RC4(128)  Mac=SHA1
```

**Comment by drwetter** [comment]
Ok, it seems I forgot (the misleading) ``-s`` option. The old ChaCha ciphers were also a difference but I didn't mention them as it seemed obvious to me that they were not included in OpenSSL 1.1.1 

Later: more.

**Pull request merged**
