### PR TITLE
Modified pr_functions to take a second argument / commentet out unused pr_functions

### PR DESCRIPTION
**Pull request by thecky**
This PR modify the pr_functions to take an optional second argument. This will be used later to print the "checkname" and the result with one function/in one line.

I also commentet out the pr_blue/grey functions - they're currently unused.

### CODE REVIEW

**Comment by thecky** [comment]
There's still a bug...I make an new PR ;)

**Comment by drwetter** [comment]
Thomas,

I don't get it, you gotta help me.

**Comment by thecky** [comment]
Hi Dirk,

till now you do sth like this for the output:
pr_bold " TLS 1.2    ";
...codelines...
pr_done_bestln "offered (OK)"

With the second arg for (in this example pr_done_bestln) we could write:
...codelines...
pr_done_bestln "offered (OK)" " TLS 1.2   "

This is imo neccessary for the severity output.
The third commit (6dcf024) just fix the bugs which I did in the first commit.

**Comment by drwetter** [comment]
@thecky: Sorry, I have another solution in mind -- let's dicuss this after next release.

**Pull request closed without merging**
