### PR TITLE
convert service name to port number

### PR DESCRIPTION
**Pull request by sanderjo**
Works with

`$ ./testssl.sh news.newshosting.com:nntps
`

### CODE REVIEW

**Comment by sanderjo** [comment]
Closes https://github.com/drwetter/testssl.sh/issues/2445

**Comment by drwetter** [comment]
Hi,
thanks first. Doesn't work on MacOS though.

```
 /tmp  getent services | wc -l
       0
 /tmp  
```

**Comment by drwetter** [comment]
MacOS has /etc/services though, don't know about WSL? We need to put some thought in this, so that the code doesn't become ugly and it works on every OS supported and on docker.

And we work around a weird bug in the old openssl we're using. I anyway wanted to complete the sieve implementation. Don't know how difficult it is yet to add/backport the service resolution into it.
 
Fallback would be a private LUT (lookup table) , i.e. ``ports2starttls()`` kind of reversed.

**Comment by drwetter** [comment]
see comment in the issue

**Pull request closed without merging**
