### PR TITLE
Allow the file output feature and mass_test feature to work together

### PR DESCRIPTION
**Pull request by seccubus**
Had to kill the run_mass_scan_parallell routine due to concurrency problems.

### CODE REVIEW

**Comment by drwetter** [comment]
@seccubus :  run_mass_testing_parallel() is currently a dead function

**Comment by seccubus** [comment]
The error was in the other function. But cannot be fixed in the parallel version.

**Comment by drwetter** [comment]
Hmm, ok.

But unless you specify one file on the command line there's no chance a file being overwritten. Is this (user error) that what you try to address?

**Comment by seccubus** [comment]
I think its is not a user error that one would expect all assessments to end up in a single file. Otherwise for a db inport one would have to iterate over several files.

**Comment by drwetter** [comment]
Ok, was checking your perspective.

Idea is fine. I need to do some tweaking on it. Bear with me.

Thx, Dirk

**Comment by seccubus** [comment]
We also need this for Seccubus integration.

**Comment by drwetter** [comment]
Thx @seccubus !

**Pull request merged**
