### PR TITLE
Update ARMv7 binary (compiled with musl libc)

### PR DESCRIPTION
**Pull request by lainegholson**
It should work on glibc systems, too. DNS also works.

### CODE REVIEW

**Comment by lainegholson** [comment]
I also signed the binary with my PGP key (id D375109C). You should verify it. Here it is:
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAABCAAGBQJXR72gAAoJEK8T7CzTdRCcHycP/2Owdz12UqnLPjm7TeujLXEg
2FODqnHxhtOGTLUMA0Cn0oTAXX7ht9BtKDPgAn/JHqVq2smnY10haRlHqub33UFK
ZsnGGLQs6eHQ1y2hfHD/B+SNjW4SNyubtrYGQl/ejU9fGWLU0SAzHLEF5mBpATyI
Uq/ZPcqZWkJus4lxwUzPWtlv+9WapcE2E5VepejLi84l2yVKzcZOz2Fg1ibdzG++
5Ws10mx5dsFRhdQqyspnV76U8DcR8hO8kWV2IGSA0UKG94hSx03N6rYA/vW2r2gL
BxMUj8acl6HEVLgmEuwXByPDYHHVhbnOVrlxalAl3nFLsodZbjQZnMSDEl1FMCzg
KvuPBFn2FSIpjrunw7Ey11HXbiobiIhCiPBlAfWwJ6O/mZxEVqmzLg3zWYfNkPI4
7G6BsJrvMBhRxhmXTfflAe6HJVTXCrYqhUMNeWv55B4iVUsjMB3vxEWUzTFRB1V1
fHmP0xWjW4Df8VlaWuvAypp2nGxxnZy4adkCqZUNnU+Do4+7DgfijfphLoyimb9s
7yWQexqIgZjssqhCjgSHQLMVFO/jk8I1DDShD8bEW9QLYJQfjZlrsLfTr41M28Tw
NPiMfUX01Xpgrgp9QvwFUfp6zya2UEqHwJPgrOlm7tMpO7f6SENltvxSUHusjUve
Dg2RQYeo+KDZRRRfrrxe
=GrV9
-----END PGP SIGNATURE-----

**Comment by drwetter** [comment]
Thx. See https://github.com/drwetter/testssl.sh/issues/362

**Comment by drwetter** [comment]
Sanitiy check: 

Q: did make report go through w/o problems? 

Q: how many ciphers does your binary list? 

Q: do you have the output of '`openssl version -a'` handy?

**Comment by drwetter** [comment]
Any chance for a check that it works with a glibc system?

**Comment by lainegholson** [comment]
`make report` runs fine
179 ciphers
openssl version -a says: `OpenSSL 1.0.2-chacha (1.0.2i-dev)
built on: Fri May 27 03:03:27 2016
platform: linux-armv4
options:  bn(64,32) md2(int) rc4(ptr,char) des(idx,cisc,16,long) idea(int) blowfish(ptr) 
compiler: gcc -I. -I.. -I../include  -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -static -DOPENSSL_USE_BUILD_DATE -DOPENSSL_USE_IPV6 -march=armv7-a -Wa,--noexecstack -O3 -Wall -DOPENSSL_EXPERIMENTAL_JPAKE -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/ssl"`

I tested it on my ancient ubuntu 14.04 LTS system, and it works fine.

**Comment by drwetter** [comment]
Thx, Laine!

Am 3. Juni 2016 03:01:12 MESZ, schrieb Laine Gholson <notifications@github.com>:
>`make report` runs fine
>179 ciphers
>openssl version -a says: `OpenSSL 1.0.2-chacha (1.0.2i-dev)
>built on: Fri May 27 03:03:27 2016
>platform: linux-armv4
>options:  bn(64,32) md2(int) rc4(ptr,char) des(idx,cisc,16,long)
>idea(int) blowfish(ptr) 
>compiler: gcc -I. -I.. -I../include  -DZLIB -DOPENSSL_THREADS
>-D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -static
>-DOPENSSL_USE_BUILD_DATE -DOPENSSL_USE_IPV6 -march=armv7-a
>-Wa,--noexecstack -O3 -Wall -DOPENSSL_EXPERIMENTAL_JPAKE
>-DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM
>-DSHA512_ASM -DAES_ASM -DBSAES_ASM -DGHASH_ASM
>OPENSSLDIR: "/etc/ssl"`
>
>I tested it on my ancient ubuntu 14.04 LTS system, and it works fine.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/drwetter/testssl.sh/pull/363#issuecomment-223465091


-- 
Set from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
Thx. See #390

**Pull request closed without merging**
