### PR TITLE
Further updates on client-sim-sockets

### PR DESCRIPTION
**Pull request by seccubus**
This PR builds on PR #386 of @dcooper16 

Enhancements:
- Client simulation data is now in a separate file
- This file can be updated with utils/update_client_sim_data.pl
  - grabs data directly from ssllabs.com
  - contains all data for both socket and openssl simulation
  - marks clients as http/ftp, http or generic
  - contains three mail clients which are not in ssllabs
- Client sims with openssl actually work correctly now
- Socket based client sims work with startssl and other non-http protocols as well for clients that support the protocol

### CODE REVIEW

**Comment by drwetter** [comment]
Thx, @seccubus !

I would rather like to postpone this to 2.9dev. Basically testssl.sh has feature freeze and top prio has the 2.8. release.

**Comment by seccubus** [comment]
I understand. This does mean that 2.8 will be pushed out with buggy client simulation code. 
When is 2.8 planned for?
Can I convince you if I write a good unit test?

**Comment by seccubus** [comment]
@dcooper16 discovered some bugs in my code that I have fixed.

**Comment by drwetter** [comment]
Hi Frank,

Am 06/29/2016 um 11:27 AM schrieb Frank Breedijk:
> I understand. This does mean that 2.8 will be pushed out with buggy client simulation code.gs

of course not.

> When is 2.8 planned for?

as soon as all bugs are squashed. Some give me a hard time. If you have
cycles left I appreciate help.

> Can I convince you if I write a good unit test?

A unit test is always very welcome....

For #375 I enabled sockets per default, if somebody tells me the results on >=15
hosts are ok, we can close that.

CheerS, Dirk

**Comment by drwetter** [comment]
What I would like to postpone to 2.9dev is the use of external file for client simulation (architecture change) and the non-HTTP checks (new  feature)

**Comment by seccubus** [comment]
I can manually copy in the data. The non-http change really is a very trivial one. There was never any technical reason to make it a http only check. For non-http it will only do simulations of java and openssl. 

Are you ok with the change if I just copy the data back into the script?

**Comment by seccubus** [comment]
@drwetter if this is pulled, then this fulfils all requirements from #393 

Another issue to close for the 2.8 milestone.

**Comment by drwetter** [comment]
Am 07/01/2016 um 08:20 PM schrieb Frank Breedijk:
> I can manually copy in the data. The non-http change really is a very trivial one. There was
> never any technical reason to make it a http only check. 

not really, we were missing the real other clients maybe.

> For non-http it will only do
> simulations of java and openssl.
> 
> Are you ok with the change if I just copy the data back into the script?

Fine with me.

I planned to have some functions external, actually for this release. But as
there were other good improvements (wink), plans were postponed...


Cheers, Dirk

**Comment by drwetter** [comment]
Just working on something else -- this is a reminder -- there ciphers in here which need to be renamed. E.g.  Android 5.0.0 has the old CHACHA/POLY ciphers (cc14,cc13) and they need to be renamed to *_OLD, see https://github.com/PeterMosmans/openssl/issues/43

**Comment by drwetter** [comment]
phew! lot's of clients in there. Thx for the work!

It also needs some attention though. Todos for the master and release:

1) work on a even shorter list for the default output. 
2) put the client data to $INSTALL_DIR/include (yes, sorry: :-)  now that I am looking at it....)
3) for some protocols the client doesn't seem to be ok (e.g. SMTP --> browsers, spiders)

Could you take care of 3? I'll can do 1. 

I created another branch for this (client_simulation). It makes my life easier and we can work faster on this.

Cheers, Dirk

**Comment by drwetter** [comment]
2 has been done

**Comment by seccubus** [comment]
Re 1.
Since the list is mostly generated by utils/update_client_sim_data.pl it would simply be a matter of tuning the logic in there to make the list shorter. The rules for determining if a client is current are as follows:

* Baidu/Bing/Google/Tor/Yahoo/Yandex -> Only latest
* Chrome -> Only latest
* Firefox -> Latest 3
* Opera -> Not current at all
* Others -> Current

This seems to match the SSLLabs logic. 

How do you want this adjusted?

**Comment by seccubus** [comment]
Re 2.
It there any way that I can pick up/view this change?
I want to make sure that update_client_sim_data.pl is in line with this.

**Comment by seccubus** [comment]
Re 3.
Can you be more precise about that is not correct?

**Comment by drwetter** [comment]
Am 21. Juli 2016 09:01:48 MESZ, schrieb Frank Breedijk <notifications@github.com>:
>Re 2.
>It there any way that I can pick up/view this change?
>I want to make sure that update_client_sim_data.pl is in line with
>this.

Pls have a look in my branch mentioned . I did I miss something?

Cheers,Dirk 


-- 
Sent from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
Am 21. Juli 2016 09:00:43 MESZ, schrieb Frank Breedijk <notifications@github.com>:
>Re 1.
>Since the list is mostly generated by utils/update_client_sim_data.pl
>it would simply be a matter of tuning the logic in there to make the
>list shorter. The rules for determining if a client is current are as
>follows:
>
>* Baidu/Bing/Google/Tor/Yahoo/Yandex -> Only latest
>* Chrome -> Only latest
>* Firefox -> Latest 3
>* Opera -> Not current at all
>* Others -> Current
>
>This seems to match the SSLLabs logic. 
>
>How do you want this adjusted?

Above sounds good. But it would make sense to me to handpick candidates  at least on the bad end, so that people know whether IE 6 e.g. can connect at all.

Let me come up with a suggestion 


Dirk


-- 
Sent from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
Am 21. Juli 2016 09:03:06 MESZ, schrieb Frank Breedijk <notifications@github.com>:
>Re 3.
>Can you be more precise about that is not correct?


Just have a swing targeting SMTP via STARTTLS.

Cheers, Dirk

-- 
Sent from my mobile. Excuse my brevity&typos

**Comment by drwetter** [comment]
wrt 1: 

first shot:

* Baidu/Bing/Google/Tor/Yahoo/Yandex -> Only latest 
* Android: 2.3.7, 5, 6
* Chrome -> Only latest 
* Firefox -> Latest + ESR 
* Opera -> latest
* IE --> 6/XP, 8/XP, IE 11 Win 7,  IE 11 Win 8.1, Win 10
* Edge 13 Win 10
* Java 7+8 --> latest
* openssl 1.0.2 --> latest 
* Safari: latest,  5.1.9

For Mac, iOS and Windows 10 I can't tell, as I have neither. Also: Is there a difference for Win 10 mobile vs. desktop? Same iOS and OSX. Though on those platforms the mobile stack is supposed to be the same.

**Comment by seccubus** [comment]
@drwetter you didn't mention the branch here, but I found it anyway... ;)

**Comment by seccubus** [comment]
Wrt 3. I fixed the protocol matching, but in an ugly way. It seems count_lines will always return at least 1 even if fed an empty string. 
I used wc -l and hope that @drwetter will patch count_lines for me because I'm afraid of side effects.

**Pull request closed without merging**
