### PR TITLE
Custom HTTP request headers support added. Addresses #1770

### PR DESCRIPTION
**Pull request by tosticated**
PR to address feature request #1770. 

- The _--customhttpheader_ parameter is supported and can be added multiple times if required. 
- A join_by() function (found at https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-an-array-in-bash/17841619#17841619) is added as a helper function.
- Documentation updated as well.

### CODE REVIEW

**Comment by drwetter** [comment]
Thanks! basically fine but to be honest both the cmd line and the global vars CUSTOMHTTPHEADER(S) got a bit too long for my taste. I'll chew on this during there days.

**Comment by tosticated** [comment]
I agree, the variable is a bit long. Perhaps something like 'reqheader'? Let me know if I need to make any changes.

**Comment by drwetter** [comment]
>  agree, the variable is a bit long. Perhaps something like 'reqheader'?

as I woke up today I was exactly thinking about that.

>  Let me know if I need to make any changes.

Yes, please. That would be great. Thanks for the Changelog too.

Then I can stash your branch I checked out.

Cheers, Dirk

**Comment by tosticated** [comment]
Alright, changed it to _reqheader_ everywhere. Should be ok to merge.

**Comment by drwetter** [comment]
Thank you!

**Pull request merged**
