### PR TITLE
update requirements in documentation

### PR DESCRIPTION
**Pull request by MFTabriz**

### CODE REVIEW

**Comment by drwetter** [comment]
Thanks, but could you please resubmit this PR w/o messing up the line formatting?

**Comment by MFTabriz** [comment]
@drwetter please re-open this PR and I'll fix the issue.

**Comment by MFTabriz** [comment]
@drwetter By the way, the rest of `doc/testssl.1.md` has been formatted as 1-line per paragraph. Shouldn't this part also follow the same style?

**Comment by drwetter** [comment]
Please just open a new PR and use an editor.

**Pull request closed without merging**
